import type { SeedQuestion } from "../types";

export const compeng: SeedQuestion[] = [
  {
    id: "ce-logic-001", topic: "digital logic", d: 2,
    q: "Which single gate type can build every other logic function?",
    a: ["NAND", "XOR", "AND", "Buffer"],
    why: "NAND (and NOR) are functionally complete, which is why whole libraries are built from them.",
  },
  {
    id: "ce-logic-002", topic: "digital logic", d: 1,
    q: "An XOR gate outputs 1 when",
    a: ["Its inputs differ", "Both inputs are 1", "Both inputs are 0", "Either input is 1"],
    why: "That difference detection is what makes XOR the heart of adders, parity and simple encryption.",
  },
  {
    id: "ce-logic-003", topic: "digital logic", d: 2,
    q: "What separates sequential logic from combinational logic?",
    a: ["Sequential logic depends on stored past state, not just present inputs", "Sequential logic is faster", "Combinational logic needs a clock", "Sequential logic uses only NAND gates"],
    why: "Memory elements are what let a circuit count, sequence or remember.",
  },
  {
    id: "ce-logic-004", topic: "digital logic", d: 3,
    q: "Why does a flip-flop specify a setup and hold time?",
    a: ["Data must be stable around the clock edge or the output can go metastable", "They set the maximum clock frequency directly", "They describe how long the output stays valid", "They define the power-up delay"],
    why: "Violate the window and the flip-flop may sit between levels for an unbounded time. Synchronisers exist to manage this risk.",
    deeper: [{
      level: 3,
      q: "You must bring an asynchronous button signal into a clocked design safely. The standard approach is",
      a: ["Two flip-flops in series as a synchroniser", "A longer clock period", "A pull-up resistor on the input", "An inverter before the register"],
      why: "The first stage may go metastable; the second stage gives it time to settle before the logic sees it.",
    }],
  },
  {
    id: "ce-logic-005", topic: "digital logic", d: 2,
    q: "De Morgan's theorem says NOT (A AND B) equals",
    a: ["(NOT A) OR (NOT B)", "(NOT A) AND (NOT B)", "A OR B", "NOT (A OR B)"],
    why: "It lets you push inversions around and redraw a circuit in whichever gate family is cheapest.",
  },
  {
    id: "ce-arch-001", topic: "architecture", d: 2,
    q: "What distinguishes a Harvard architecture from von Neumann?",
    a: ["Separate memories and buses for instructions and data", "It has no cache", "It uses only registers", "Instructions are fixed width"],
    why: "Separate buses let a fetch and a data access happen at once, which is why many microcontrollers and DSPs use it.",
  },
  {
    id: "ce-arch-002", topic: "architecture", d: 2,
    q: "Pipelining a processor improves",
    a: ["Throughput, by overlapping stages of successive instructions", "The latency of each individual instruction", "Cache hit rate", "Memory bandwidth"],
    why: "One instruction still takes as long or longer. More of them finish per second.",
  },
  {
    id: "ce-arch-003", topic: "architecture", d: 2,
    q: "Why does a branch hurt a deeply pipelined CPU?",
    a: ["Work already begun on the wrong path must be thrown away", "Branches take more memory to fetch", "The pipeline must be flushed on every branch, always", "Branch instructions are slower to decode"],
    why: "Predictors get most branches right; the cost only appears on a mispredict, and it scales with pipeline depth.",
  },
  {
    id: "ce-arch-004", topic: "architecture", d: 2,
    q: "A superscalar CPU is one that",
    a: ["Issues more than one instruction per clock cycle", "Runs at a higher clock frequency", "Has more than one core", "Uses a wider data bus"],
    why: "Multiple execution units exploit instruction-level parallelism inside a single thread.",
  },
  {
    id: "ce-arch-005", topic: "architecture", d: 2,
    q: "Little-endian storage means the",
    a: ["Least significant byte sits at the lowest address", "Most significant byte sits at the lowest address", "Bytes are stored in reverse bit order", "Words are always aligned"],
    why: "It only matters when bytes cross a boundary — a file, a network packet, another architecture.",
  },
  {
    id: "ce-arch-006", topic: "architecture", d: 3,
    q: "What problem does a memory management unit solve?",
    a: ["It maps each process's virtual addresses to physical memory, isolating them", "It speeds up cache lookups", "It handles DMA transfers", "It arbitrates between cores"],
    why: "Translation gives protection and lets a program see a private, contiguous address space it does not actually own.",
  },
  {
    id: "ce-arch-007", topic: "architecture", d: 2,
    q: "DMA is valuable because it lets a peripheral",
    a: ["Move data to and from memory without the CPU copying every byte", "Run its own instruction set", "Access the internet directly", "Interrupt at higher priority"],
    why: "The CPU sets up the transfer and goes back to work, getting one interrupt when it completes.",
  },
  {
    id: "ce-arch-008", topic: "architecture", d: 2,
    q: "The classic argument for RISC over CISC was that",
    a: ["Simple, uniform instructions pipeline and optimise more easily", "Fewer instructions means smaller programs", "It removes the need for a compiler", "It allows variable-length encoding"],
    why: "Modern high-end CISC chips translate internally into RISC-like operations, so the line has blurred.",
  },
  {
    id: "ce-mem-001", topic: "memory", d: 2,
    q: "Why does DRAM need periodic refresh while SRAM does not?",
    a: ["DRAM stores each bit as charge on a capacitor that leaks away", "DRAM runs at a lower voltage", "SRAM is non-volatile", "DRAM has no transistors"],
    why: "One transistor and one capacitor per bit makes DRAM dense and cheap; SRAM's six transistors hold state as long as power lasts.",
  },
  {
    id: "ce-mem-002", topic: "memory", d: 1,
    q: "Cache works because real programs show",
    a: ["Locality — they reuse recent data and nearby addresses", "Uniformly random access", "Mostly sequential writes", "Very small working sets only"],
    why: "Temporal and spatial locality are what make a small fast memory look like a large one.",
    deeper: [{
      level: 3,
      q: "Walking a huge array with a large stride is far slower than walking it sequentially. Why?",
      a: ["Each access pulls in a cache line but uses only one word of it", "Large strides trigger a page fault every time", "The prefetcher disables itself on any stride", "Sequential access uses a different bus"],
      why: "You pay for a whole line and throw most of it away, so effective bandwidth collapses.",
    }],
  },
  {
    id: "ce-mem-003", topic: "memory", d: 2,
    q: "Flash memory wears out because",
    a: ["Each erase cycle degrades the oxide that traps charge", "Its capacitors dry out with age", "It is refreshed too often", "Reading slowly erases it"],
    why: "Wear levelling spreads erases across blocks so no single one dies early.",
  },
  {
    id: "ce-mem-004", topic: "memory", d: 2,
    q: "Order these from fastest to slowest access.",
    a: ["Register, L1 cache, DRAM, SSD", "L1 cache, register, SSD, DRAM", "DRAM, register, L1 cache, SSD", "Register, DRAM, L1 cache, SSD"],
    why: "Each step down the hierarchy is roughly an order of magnitude slower and much larger.",
  },
  {
    id: "ce-emb-001", topic: "embedded systems", d: 2,
    q: "What is a watchdog timer for?",
    a: ["Resetting the system if software stops petting it on schedule", "Measuring how long tasks take", "Waking the CPU from sleep periodically", "Timing out serial reads"],
    why: "It is the last line of defence for a device nobody can reach to power-cycle.",
  },
  {
    id: "ce-emb-002", topic: "embedded systems", d: 2,
    q: "Why should an interrupt service routine stay short?",
    a: ["It blocks or delays other interrupts and the main program", "Long routines use too much flash", "The compiler cannot optimise long ISRs", "Interrupts expire after a fixed time"],
    why: "Set a flag or queue the work; do the heavy lifting in the main loop.",
  },
  {
    id: "ce-emb-003", topic: "embedded systems", d: 3,
    q: "A C variable changed inside an ISR must be declared volatile because otherwise",
    a: ["The compiler may cache it in a register and never notice the change", "It would be stored in flash", "The linker places it incorrectly", "Interrupts cannot write to normal variables"],
    why: "volatile forces a real memory access each time. It does not, however, make the access atomic.",
    deeper: [{
      level: 3,
      q: "A 32-bit counter written by an ISR is read in the main loop on an 8-bit MCU, and occasionally a wild value appears. The fix is",
      a: ["Briefly disable interrupts around the multi-byte read", "Mark the variable const", "Make the ISR longer so it finishes first", "Use a faster clock"],
      why: "The read is several instructions, so an interrupt can land mid-way and tear the value. volatile alone does not help.",
    }],
  },
  {
    id: "ce-emb-004", topic: "embedded systems", d: 1,
    q: "A mechanical button read by a microcontroller usually needs debouncing because",
    a: ["The contacts chatter for a few milliseconds when they close", "The input pin is too sensitive", "The pull-up resistor is too weak", "The ADC samples too slowly"],
    why: "One press can register as a dozen. A short delay, a state machine or an RC filter settles it.",
  },
  {
    id: "ce-emb-005", topic: "embedded systems", d: 2,
    q: "Why does a microcontroller input pin often need a pull-up resistor?",
    a: ["An unconnected input floats and reads unpredictably", "It limits current into the pin", "It converts the signal to analogue", "It protects against static only"],
    why: "The resistor defines the idle level so the switch only has to pull the pin low.",
  },
  {
    id: "ce-emb-006", topic: "microcontrollers", d: 2,
    q: "How does a microcontroller differ from a microprocessor?",
    a: ["It integrates memory and peripherals on the same chip", "It runs faster", "It cannot execute interrupts", "It has no registers"],
    why: "One chip, a few passives and a power supply becomes a working system.",
  },
  {
    id: "ce-emb-007", topic: "microcontrollers", d: 2,
    q: "What is a bootloader on a microcontroller for?",
    a: ["Receiving new firmware and writing it to flash without a programmer", "Booting the operating system", "Initialising the clock tree", "Checking RAM at startup"],
    why: "It is why a board can be updated over USB or serial in the field.",
  },
  {
    id: "ce-emb-008", topic: "microcontrollers", d: 2,
    q: "A PWM output controls LED brightness by varying",
    a: ["The fraction of each cycle the output is high", "The output voltage continuously", "The switching frequency", "The current limit resistor"],
    why: "Switching fully on and off wastes almost nothing, and the eye averages the result.",
  },
  {
    id: "ce-bus-001", topic: "serial buses", d: 2,
    q: "UART is called asynchronous because",
    a: ["No clock line is shared; both ends must agree on the baud rate in advance", "Data can arrive in any order", "It is full duplex", "It has no start bit"],
    why: "The start bit lets the receiver align, then it samples on its own timebase — which is why a wrong baud rate gives garbage.",
  },
  {
    id: "ce-bus-002", topic: "serial buses", d: 2,
    q: "How does SPI select which peripheral is being addressed?",
    a: ["A separate chip-select line per device", "An address byte at the start of each transfer", "A unique clock frequency per device", "Round-robin timing slots"],
    why: "That is why SPI is fast and simple but costs a pin for every device you add.",
  },
  {
    id: "ce-bus-003", topic: "serial buses", d: 2,
    q: "Why do I²C lines need pull-up resistors?",
    a: ["Devices can only pull the line low, never drive it high", "The bus voltage is too low otherwise", "They set the clock frequency", "They protect against short circuits"],
    why: "Open-drain drivers make it safe for many devices to share two wires, and let any of them stretch the clock.",
    deeper: [{
      level: 3,
      q: "An I²C bus works at 100 kHz but fails at 400 kHz with rounded-off edges. The most likely cause is",
      a: ["Pull-up resistors too weak for the bus capacitance", "Wrong device addresses", "A missing ground connection", "Too few devices on the bus"],
      why: "Rise time is set by the RC of the pull-up and the bus capacitance. Stronger pull-ups sharpen the edges.",
    }],
  },
  {
    id: "ce-bus-004", topic: "serial buses", d: 2,
    q: "Which of these buses is full duplex by design?",
    a: ["SPI", "I²C", "CAN", "1-Wire"],
    why: "SPI shifts data out and in on separate lines during the same clock pulses.",
  },
  {
    id: "ce-bus-005", topic: "serial buses", d: 3,
    q: "Two CAN nodes start transmitting at once. What happens?",
    a: ["The lower-numbered identifier wins and the other backs off without losing data", "Both abort and retry after a random delay", "The messages collide and are lost", "The bus master arbitrates a winner"],
    why: "Dominant bits overwrite recessive ones, so arbitration is non-destructive and priority is built into the identifier.",
  },
  {
    id: "ce-bus-006", topic: "serial buses", d: 2,
    q: "CAN uses a differential pair mainly to",
    a: ["Reject the common-mode noise found in a vehicle", "Double the data rate", "Carry power alongside data", "Allow longer addresses"],
    why: "Noise hits both wires equally and subtracts out at the receiver.",
  },
  {
    id: "ce-bus-007", topic: "serial buses", d: 2,
    q: "A CAN bus needs 120-ohm resistors at both ends because",
    a: ["They match the cable impedance and stop reflections", "They limit current through the transceivers", "They set the bit rate", "They bias the recessive level"],
    why: "One resistor at each end, not one per node — a common wiring mistake.",
  },
  {
    id: "ce-bus-008", topic: "USB", d: 2,
    q: "USB is host-centric, which means",
    a: ["Devices never transmit until the host asks them to", "Only one device can be attached at a time", "Devices must be self-powered", "Data flows in one direction only"],
    why: "Scheduling everything from the host keeps the protocol simple and deterministic, but needs USB OTG or a dual-role port for device-to-device links.",
  },
  {
    id: "ce-bus-009", topic: "USB", d: 2,
    q: "What happens during USB enumeration?",
    a: ["The host assigns an address and reads descriptors to learn what the device is", "The device negotiates its supply voltage", "The cable's length is measured", "The device loads its driver onto the host"],
    why: "Descriptors tell the host which class driver to bind, which is why a standard keyboard needs no installation.",
  },
  {
    id: "ce-pcb-001", topic: "PCB design", d: 2,
    q: "Why does a decoupling capacitor belong as close to the supply pin as possible?",
    a: ["Trace inductance between cap and pin defeats its purpose", "It looks tidier in the layout", "It keeps the capacitor cool", "It reduces the trace's resistance"],
    why: "The cap supplies the fast current spike locally; every millimetre of trace adds inductance that slows delivery.",
  },
  {
    id: "ce-pcb-002", topic: "PCB design", d: 3,
    q: "A fast signal's return current on a board with a solid ground plane flows",
    a: ["Directly under the trace, following the path of least inductance", "Along the shortest straight line to the supply", "Evenly spread across the whole plane", "Back through the power plane"],
    why: "This is why a split or slot in the plane under a fast trace causes so much trouble — the return has to detour.",
    deeper: [{
      level: 3,
      q: "Given that, why is a gap cut in the ground plane beneath a high-speed trace so damaging?",
      a: ["The return current must loop around the gap, creating a large radiating loop", "It raises the trace's DC resistance", "It shorts the signal to ground", "It changes the trace's colour code"],
      why: "A big loop area means emissions and susceptibility. Keep the reference plane continuous under fast signals.",
    }],
  },
  {
    id: "ce-pcb-003", topic: "PCB design", d: 2,
    q: "Trace width on a PCB is chosen mainly by",
    a: ["The current it must carry and the temperature rise allowed", "The board's colour", "The number of vias nearby", "The solder mask thickness"],
    why: "Impedance control adds a second constraint on high-speed traces, set by width, height above the plane and dielectric.",
  },
  {
    id: "ce-pcb-004", topic: "PCB design", d: 2,
    q: "What is a via?",
    a: ["A plated hole connecting traces on different layers", "A test point for a probe", "A gap in the solder mask", "A component footprint"],
    why: "Vias add inductance and discontinuity, so high-speed designs use as few as they can get away with.",
  },
  {
    id: "ce-si-001", topic: "signal integrity", d: 3,
    q: "A digital edge reflects partway down a long trace. The cause is",
    a: ["An impedance discontinuity between source, trace and load", "Too much current in the trace", "Insufficient supply voltage", "A slow clock frequency"],
    why: "Once edges are fast enough that the trace behaves as a transmission line, matching matters just as it does in RF.",
  },
  {
    id: "ce-si-002", topic: "signal integrity", d: 2,
    q: "Deliberately slowing an output's slew rate usually",
    a: ["Reduces emissions and ringing", "Increases the maximum data rate", "Lowers the supply current at DC", "Improves setup time margin"],
    why: "Harmonic content falls with edge speed. Use the slowest edge that still meets timing.",
  },
  {
    id: "ce-si-003", topic: "signal integrity", d: 2,
    q: "Crosstalk between two adjacent traces is reduced most simply by",
    a: ["Increasing the spacing between them", "Making both traces wider", "Adding series resistors to both", "Raising the supply voltage"],
    why: "Coupling falls sharply with separation, and a ground trace or plane between them helps further.",
  },
  {
    id: "ce-pwr-001", topic: "power electronics", d: 2,
    q: "Why is a switching regulator usually far more efficient than a linear one?",
    a: ["The pass device is either fully on or fully off, so it dissipates little", "It operates at a lower voltage", "It uses no inductor", "It has no output capacitor"],
    why: "A linear regulator burns the voltage difference times the current as heat, every moment it runs.",
    deeper: [{
      level: 2,
      q: "So when is a linear regulator still the better choice?",
      a: ["Small voltage drops, low current, or where switching noise is unacceptable", "High-current conversions from a high input voltage", "Battery chargers", "Anywhere efficiency matters most"],
      why: "Linear regulators are quiet, cheap and simple. For a sensitive analogue rail that is often worth the heat.",
    }],
  },
  {
    id: "ce-pwr-002", topic: "power electronics", d: 2,
    q: "A buck converter produces an output that is",
    a: ["Lower than its input voltage", "Higher than its input voltage", "Of opposite polarity", "Always isolated from its input"],
    why: "A boost raises the voltage; a buck-boost can do either side of the input.",
  },
  {
    id: "ce-pwr-003", topic: "power electronics", d: 2,
    q: "A flyback diode across a relay coil exists to",
    a: ["Give the coil's collapsing current a path instead of a destructive voltage spike", "Limit the coil's steady current", "Speed up the relay's release", "Rectify the supply"],
    why: "Inductor current cannot stop instantly, so without a path the voltage rises until something breaks down.",
  },
  {
    id: "ce-pwr-004", topic: "power electronics", d: 3,
    q: "Switching a MOSFET faster generally reduces",
    a: ["Switching loss, at the cost of more EMI and ringing", "Conduction loss", "Gate charge required", "Output ripple voltage"],
    why: "The device dissipates most during the transition, so shortening it saves energy — but sharp edges radiate.",
  },
  {
    id: "ce-sens-001", topic: "sensors", d: 2,
    q: "A 12-bit ADC divides its reference range into how many steps?",
    a: ["4096", "144", "1024", "12"],
    why: "Two to the twelfth. Resolution is only useful if the reference and the noise floor are good enough to match it.",
  },
  {
    id: "ce-sens-002", topic: "sensors", d: 2,
    q: "An NTC thermistor's resistance as it warms up",
    a: ["Falls", "Rises", "Stays constant", "Rises then falls"],
    why: "Negative temperature coefficient. A PTC device does the opposite and is often used as a resettable fuse.",
  },
  {
    id: "ce-sens-003", topic: "sensors", d: 2,
    q: "A Hall effect sensor detects",
    a: ["Magnetic field, via a voltage across a current-carrying strip", "Temperature change", "Light intensity", "Mechanical strain"],
    why: "It gives contactless position and speed sensing — brushless motors, wheel speed, lid switches.",
  },
  {
    id: "ce-sens-004", topic: "sensors", d: 2,
    q: "A MEMS accelerometer sitting flat and still on a bench reads about 1 g on its vertical axis. Why?",
    a: ["It measures proper acceleration, so it senses the support force holding it up", "It is poorly calibrated", "It is detecting vibration in the bench", "It measures velocity, not acceleration"],
    why: "In free fall the same sensor reads zero. That is the basis of every drop detector.",
  },
  {
    id: "ce-elec-001", topic: "electronics", d: 1,
    q: "A resistor in series with an LED is there to",
    a: ["Limit the current through it", "Drop the voltage to zero", "Protect against reverse polarity", "Set the colour"],
    why: "An LED's current rises steeply past its forward voltage, so without the resistor it destroys itself.",
  },
  {
    id: "ce-elec-002", topic: "electronics", d: 2,
    q: "What does an operational amplifier with negative feedback try to do?",
    a: ["Drive its two inputs to the same voltage", "Maximise its output voltage", "Amplify by its full open-loop gain", "Oscillate at a fixed frequency"],
    why: "The virtual short is the shortcut behind almost every op-amp circuit analysis.",
  },
  {
    id: "ce-elec-003", topic: "electronics", d: 2,
    q: "A bypass capacitor and a bulk capacitor on a supply rail differ in that the bypass cap",
    a: ["Is small and fast, handling high-frequency transients", "Stores more total energy", "Filters the mains input", "Blocks DC from the rail"],
    why: "Big electrolytics are slow; small ceramics respond quickly. Boards need both.",
  },
];
