import type { SeedQuestion } from "../types";

export const economics: SeedQuestion[] = [
  {
    id: "ec-sc-001", topic: "scarcity and choice", d: 1,
    q: "The fundamental economic problem is that",
    a: ["Wants are unlimited while resources are limited", "Money is unevenly distributed", "Governments spend too much", "Prices keep rising"],
    why: "Scarcity forces choice, and choice is what economics studies. Even a rich society faces it.",
  },
  {
    id: "ec-sc-002", topic: "scarcity and choice", d: 1,
    q: "You spend Saturday at a free concert instead of working a shift worth $120. Your opportunity cost is",
    a: ["The $120 you gave up", "Zero, since the concert was free", "The price of a concert ticket", "The $120 plus your travel time only"],
    why: "Opportunity cost is the value of the best alternative forgone, whether or not money changes hands.",
  },
  {
    id: "ec-sc-003", topic: "scarcity and choice", d: 2,
    q: "A production possibilities curve bows outward because",
    a: ["Resources are not equally suited to both goods, so costs rise as you shift more", "Technology improves over time", "Consumers prefer variety", "Both goods have constant costs"],
    why: "Increasing opportunity cost: the first workers you move across are the best-suited, and later ones are not.",
    deeper: [{
      level: 3,
      q: "A country discovers a new technology that improves only one of its two goods. What happens to the curve?",
      a: ["It shifts outward along that good's axis only, pivoting", "The whole curve shifts outward evenly", "The curve becomes a straight line", "Nothing changes until demand rises"],
      why: "A point inside the curve means unemployed or misallocated resources; the curve itself moves only with resources or technology.",
    }],
  },
  {
    id: "ec-sc-004", topic: "scarcity and choice", d: 2,
    q: "A sunk cost should be treated how in a rational decision?",
    a: ["Ignored, because it cannot be recovered either way", "Added to the cost of continuing", "Subtracted from expected benefits", "Weighted by how recently it was spent"],
    why: "Only future costs and benefits differ between the options. That is marginal thinking.",
  },
  {
    id: "ec-sd-001", topic: "supply and demand", d: 1,
    q: "The price of coffee rises and people buy less of it. That movement is caused by",
    a: ["A change in price, so it is a movement along the demand curve", "A shift of the demand curve leftward", "A shift of the supply curve leftward", "A change in consumer taste"],
    why: "Price moves you along a curve. Anything else — income, tastes, substitutes — shifts the whole curve.",
  },
  {
    id: "ec-sd-002", topic: "supply and demand", d: 2,
    q: "Tea becomes much cheaper. In the coffee market this is",
    a: ["A leftward shift of demand, since tea is a substitute", "A movement along the coffee demand curve", "A rightward shift of coffee supply", "No change at all"],
    why: "Substitutes shift demand for each other; complements shift it the opposite way.",
  },
  {
    id: "ec-sd-003", topic: "supply and demand", d: 2,
    q: "A price set below equilibrium produces",
    a: ["A shortage, because quantity demanded exceeds quantity supplied", "A surplus", "A new higher equilibrium", "No effect if the good is a necessity"],
    why: "Rent control is the standard example: cheaper for those who have a unit, scarcer for everyone else.",
  },
  {
    id: "ec-sd-004", topic: "supply and demand", d: 2,
    q: "A binding minimum wage is a price floor in the labour market, so economists expect",
    a: ["Quantity of labour supplied to exceed quantity demanded at that wage", "Employment to rise at every firm", "The wage to fall back to equilibrium", "No measurable effect on any market"],
    why: "The size of the effect is empirically contested, especially where employers have wage-setting power, but the mechanism is the standard model.",
  },
  {
    id: "ec-sd-005", topic: "supply and demand", d: 2,
    q: "What does 'ceteris paribus' let an economist do?",
    a: ["Isolate one variable's effect by holding the others constant", "Assume markets always clear", "Predict the future path of prices", "Ignore government intervention"],
    why: "It is an analytical device, not a claim that the world holds still.",
  },
  {
    id: "ec-el-001", topic: "elasticity", d: 2,
    q: "Demand for a good is described as inelastic. That means",
    a: ["Quantity demanded responds weakly to a price change", "The good has many substitutes", "Demand falls to zero above a certain price", "Suppliers cannot adjust output"],
    why: "Necessities with few substitutes — insulin, gasoline in the short run — behave this way.",
  },
  {
    id: "ec-el-002", topic: "elasticity", d: 3,
    q: "A firm raises its price and total revenue goes up. Demand over that range must be",
    a: ["Inelastic", "Elastic", "Unit elastic", "Perfectly elastic"],
    why: "When demand is inelastic the price rise outweighs the quantity loss. With elastic demand, revenue would have fallen.",
    deeper: [{
      level: 3,
      q: "Why do governments tax tobacco and fuel rather than, say, restaurant meals, when the goal is stable revenue?",
      a: ["Inelastic demand means the tax raises revenue without collapsing sales", "Those goods have the most elastic demand", "They are produced domestically", "They are consumed mainly by high earners"],
      why: "The same inelasticity that makes the revenue stable also makes the tax fall heavily on those who cannot easily cut back.",
    }],
  },
  {
    id: "ec-el-003", topic: "elasticity", d: 2,
    q: "Demand for a good generally becomes more elastic when",
    a: ["Consumers have more time to find substitutes", "The good takes a smaller share of income", "Fewer substitutes exist", "It is classified as a necessity"],
    why: "Gasoline demand barely moves in a week and moves a great deal over a decade.",
  },
  {
    id: "ec-el-004", topic: "elasticity", d: 2,
    q: "A good with negative income elasticity of demand is called",
    a: ["An inferior good", "A luxury good", "A complement", "A public good"],
    why: "As income rises, people buy less of it and switch to something they prefer.",
  },
  {
    id: "ec-mkt-001", topic: "market structures", d: 2,
    q: "In perfect competition, an individual firm is a price taker because",
    a: ["Its output is tiny relative to the market and the product is identical", "Regulators set the price", "It has no fixed costs", "Consumers have no information"],
    why: "Charge a cent more and buyers go elsewhere, since nothing distinguishes your product.",
  },
  {
    id: "ec-mkt-002", topic: "market structures", d: 2,
    q: "What most distinguishes monopolistic competition from perfect competition?",
    a: ["Products are differentiated, giving each firm some pricing power", "There are only a handful of firms", "Entry is blocked", "Firms collude on price"],
    why: "Restaurants and hairdressers fit: many sellers, easy entry, but each offering is a little different.",
  },
  {
    id: "ec-mkt-003", topic: "market structures", d: 2,
    q: "Oligopoly firms watch each other closely because",
    a: ["Each firm's best move depends on what its few rivals do", "They are legally required to", "They share the same costs", "They sell identical products by law"],
    why: "Interdependence is the defining feature, and it is why game theory is the natural tool.",
  },
  {
    id: "ec-ext-001", topic: "externalities", d: 2,
    q: "A factory pollutes a river without paying for the damage. The market will therefore",
    a: ["Produce more than the socially optimal quantity", "Produce less than the socially optimal quantity", "Shut the factory down", "Reach the efficient outcome anyway"],
    why: "Private cost sits below social cost, so the price is too low and output too high.",
    deeper: [{
      level: 3,
      q: "A carbon tax is meant to fix that by",
      a: ["Making the polluter's private cost include the external cost", "Banning the activity outright", "Subsidising affected households only", "Raising government revenue as its primary purpose"],
      why: "Internalising the externality moves the market toward the efficient quantity rather than prohibiting the activity.",
    }],
  },
  {
    id: "ec-ext-002", topic: "externalities", d: 2,
    q: "Vaccination creates a positive externality, so an unregulated market tends to",
    a: ["Under-provide it relative to the social optimum", "Over-provide it", "Price it efficiently", "Provide it only to the wealthy"],
    why: "Buyers weigh only their own benefit, not the protection they give others — hence subsidies and public programmes.",
  },
  {
    id: "ec-ext-003", topic: "externalities", d: 2,
    q: "A public good is defined by being",
    a: ["Non-rival and non-excludable", "Provided by government", "Free to produce", "Available only to citizens"],
    why: "National defence is the classic case, and non-excludability is what creates the free-rider problem.",
  },
  {
    id: "ec-ext-004", topic: "externalities", d: 3,
    q: "The tragedy of the commons describes a resource that is",
    a: ["Rival but non-excludable, so each user has an incentive to overuse it", "Non-rival and excludable", "Owned by government and underused", "Too cheap to produce"],
    why: "Each fisher's extra catch costs everyone a little and benefits them fully. Fisheries collapse on exactly that arithmetic.",
  },
  {
    id: "ec-gdp-001", topic: "GDP and growth", d: 1,
    q: "GDP measures the market value of",
    a: ["All final goods and services produced within a country in a period", "All goods sold, including used ones", "All income earned by citizens anywhere", "All transactions in an economy"],
    why: "Counting only final goods avoids double-counting the intermediate ones.",
  },
  {
    id: "ec-gdp-002", topic: "GDP and growth", d: 2,
    q: "Real GDP differs from nominal GDP in that real GDP",
    a: ["Is adjusted for price changes", "Excludes government spending", "Counts only goods, not services", "Is measured per person"],
    why: "Without that adjustment you cannot tell growth in output from growth in prices.",
  },
  {
    id: "ec-gdp-003", topic: "GDP and growth", d: 2,
    q: "The expenditure approach to GDP adds consumption, investment, government spending and",
    a: ["Exports minus imports", "Exports plus imports", "Savings", "Transfer payments"],
    why: "Imports are subtracted because they were produced elsewhere, not because trade deficits reduce output.",
  },
  {
    id: "ec-gdp-004", topic: "GDP and growth", d: 2,
    q: "Which is the strongest criticism of GDP per capita as a welfare measure?",
    a: ["It ignores distribution, unpaid work and environmental damage", "It is measured too frequently", "It excludes services", "It cannot be compared across years"],
    why: "It was designed as a production measure, and it does that job well. Living standards are a different question.",
  },
  {
    id: "ec-inf-001", topic: "inflation", d: 1,
    q: "Canada's Consumer Price Index tracks",
    a: ["The cost of a fixed basket of goods a typical household buys", "The prices producers charge each other", "Wages across the economy", "Housing prices only"],
    why: "A fixed basket makes the comparison meaningful over time, though it does miss substitution and quality change.",
  },
  {
    id: "ec-inf-002", topic: "inflation", d: 2,
    q: "Demand-pull inflation arises when",
    a: ["Spending outruns the economy's capacity to produce", "Input costs such as oil rise sharply", "Supply chains break down", "The currency appreciates"],
    why: "Cost-push is the other case, and it is harder to treat because output falls while prices rise.",
  },
  {
    id: "ec-inf-003", topic: "inflation", d: 2,
    q: "Unexpected inflation generally benefits",
    a: ["Borrowers with fixed-rate loans", "Savers holding cash", "Pensioners on fixed nominal incomes", "Lenders at fixed rates"],
    why: "Debts are repaid in money that buys less than it did. Lenders and fixed-income holders take the loss.",
  },
  {
    id: "ec-inf-004", topic: "inflation", d: 3,
    q: "Your savings earn 4% while inflation runs at 6%. Your real return is",
    a: ["Negative, about minus 2%", "Positive, about 4%", "Positive, about 10%", "Zero"],
    why: "Real rate is roughly nominal minus inflation. Purchasing power is what actually matters.",
  },
  {
    id: "ec-inf-005", topic: "inflation", d: 2,
    q: "Why do central banks treat sustained deflation as dangerous?",
    a: ["Falling prices encourage households to delay spending and raise the real value of debt", "It always causes currency collapse", "It makes exports uncompetitive", "It cannot be measured accurately"],
    why: "A demand slump and a rising debt burden feed each other, and interest rates cannot fall far below zero to fight it.",
  },
  {
    id: "ec-un-001", topic: "unemployment", d: 2,
    q: "A welder laid off because a plant automated its line is experiencing which unemployment?",
    a: ["Structural", "Frictional", "Cyclical", "Seasonal"],
    why: "The skills no longer match the jobs available, so retraining or relocation is needed rather than time.",
  },
  {
    id: "ec-un-002", topic: "unemployment", d: 2,
    q: "Unemployment that rises during a recession and falls in a boom is",
    a: ["Cyclical", "Frictional", "Structural", "Seasonal"],
    why: "This is the type fiscal and monetary policy aim at. The others need different tools.",
  },
  {
    id: "ec-un-003", topic: "unemployment", d: 3,
    q: "A discouraged worker stops looking for a job. The official unemployment rate",
    a: ["Falls, because they leave the labour force entirely", "Rises", "Is unchanged", "Becomes undefined"],
    why: "Only those actively searching count as unemployed, which is why the participation rate is read alongside it.",
  },
  {
    id: "ec-un-004", topic: "unemployment", d: 2,
    q: "Why is 'full employment' not defined as zero unemployment?",
    a: ["Some frictional and structural unemployment is normal and even healthy", "Statistics are never that precise", "Governments prefer a margin", "Zero is impossible only in small countries"],
    why: "People change jobs and industries change shape. The natural rate reflects that churn.",
  },
  {
    id: "ec-fis-001", topic: "fiscal policy", d: 2,
    q: "Expansionary fiscal policy means the government",
    a: ["Raises spending or cuts taxes to boost demand", "Raises interest rates", "Sells bonds to shrink the money supply", "Cuts spending to balance the budget"],
    why: "Fiscal policy is the spending-and-taxing lever, held by government rather than the central bank.",
  },
  {
    id: "ec-fis-002", topic: "fiscal policy", d: 2,
    q: "Employment insurance payments rise automatically in a downturn. Economists call this",
    a: ["An automatic stabiliser", "Discretionary policy", "Crowding out", "A supply-side measure"],
    why: "No new legislation is needed, so the support arrives without the usual policy lag.",
  },
  {
    id: "ec-fis-003", topic: "fiscal policy", d: 2,
    q: "The difference between a budget deficit and the national debt is that a deficit is",
    a: ["A single year's shortfall, while debt is the accumulated total", "Owed abroad, while debt is owed domestically", "Always larger than the debt", "Measured in real terms only"],
    why: "A country can run a deficit while its debt-to-GDP ratio falls, if the economy grows faster than the borrowing.",
  },
  {
    id: "ec-fis-004", topic: "fiscal policy", d: 3,
    q: "The spending multiplier is larger when",
    a: ["Households spend a greater share of each extra dollar of income", "Taxes are higher", "More of the spending goes on imports", "Interest rates rise in response"],
    why: "Leakages — saving, taxes and imports — shrink each successive round of re-spending.",
  },
  {
    id: "ec-mon-001", topic: "monetary policy", d: 2,
    q: "The Bank of Canada's main policy tool is",
    a: ["The target for the overnight interest rate", "The income tax rate", "The federal budget", "Tariff levels"],
    why: "Moving the overnight rate ripples into lending rates across the economy.",
  },
  {
    id: "ec-mon-002", topic: "monetary policy", d: 2,
    q: "The Bank of Canada's inflation target is",
    a: ["2%, the midpoint of a 1 to 3 percent band", "0%", "5%", "Whatever the government sets each year"],
    why: "A credible, announced target anchors expectations, which is much of how it works.",
  },
  {
    id: "ec-mon-003", topic: "monetary policy", d: 2,
    q: "A central bank raising rates to fight inflation is relying on",
    a: ["More expensive borrowing cooling spending and investment", "Direct price controls", "Higher taxes on consumers", "A stronger currency alone"],
    why: "The effect works with a lag of several quarters, which is what makes the timing so difficult.",
    deeper: [{
      level: 3,
      q: "Why is that lag a serious problem for policymakers?",
      a: ["Rates set for today's data may bite only after conditions have changed", "It makes the tool ineffective at any horizon", "It only matters under fixed exchange rates", "It prevents the bank from ever cutting rates"],
      why: "Overtightening into a slowdown, or easing into a recovery, is a recurring risk of acting on lagging information.",
    }],
  },
  {
    id: "ec-bank-001", topic: "banking and money", d: 2,
    q: "Under fractional reserve banking, commercial banks",
    a: ["Create new deposit money when they lend", "Lend out only money already deposited, one for one", "Print physical currency", "Must hold all deposits as cash"],
    why: "A loan credits an account, and that credit is money. This is the main channel by which the money supply grows.",
  },
  {
    id: "ec-bank-002", topic: "banking and money", d: 2,
    q: "Money's three classic functions are a medium of exchange, a store of value, and",
    a: ["A unit of account", "A source of income", "A form of credit", "A government liability"],
    why: "Hyperinflation destroys the store-of-value and unit-of-account roles first, which is why prices get quoted in foreign currency.",
  },
  {
    id: "ec-bank-003", topic: "banking and money", d: 2,
    q: "A central bank acting as lender of last resort means it",
    a: ["Lends to solvent banks facing a sudden liquidity crunch", "Guarantees every bank against failure", "Lends to households directly", "Takes over failing banks"],
    why: "The aim is to stop a temporary panic from destroying an otherwise sound institution.",
  },
  {
    id: "ec-trade-001", topic: "trade", d: 3,
    q: "Comparative advantage says two countries can both gain from trade when",
    a: ["Their opportunity costs of producing goods differ", "One is better at producing everything", "Their wage levels are equal", "They produce identical goods"],
    why: "Ricardo's insight: even a country worse at everything gains by specialising where it gives up the least.",
    deeper: [{
      level: 3,
      q: "Country A can produce both wheat and cloth more cheaply than Country B in absolute terms. Should they still trade?",
      a: ["Yes, if their relative costs differ", "No, A should produce both itself", "Only if B subsidises its exports", "Only with a tariff to balance it"],
      why: "Absolute advantage in everything does not eliminate the gains. Relative cost is what drives specialisation.",
    }],
  },
  {
    id: "ec-trade-002", topic: "trade", d: 2,
    q: "A tariff on imported steel most directly benefits",
    a: ["Domestic steel producers, at the expense of steel-using industries and consumers", "All domestic industries equally", "Foreign producers", "Consumers, through lower prices"],
    why: "Protection concentrates the benefit and spreads the cost, which is a large part of why it is politically durable.",
  },
  {
    id: "ec-trade-003", topic: "trade", d: 2,
    q: "An import quota differs from a tariff in that a quota",
    a: ["Caps the quantity allowed in rather than taxing it", "Raises government revenue directly", "Applies only to services", "Is illegal under all trade agreements"],
    why: "Both raise domestic prices, but a tariff collects revenue while a quota usually hands the windfall to whoever holds the licence.",
  },
  {
    id: "ec-fx-001", topic: "exchange rates", d: 2,
    q: "The Canadian dollar appreciates against the US dollar. For Canadian exporters this means",
    a: ["Their goods become more expensive for American buyers", "Their goods become cheaper abroad", "Nothing, since prices are set in Canada", "Lower input costs and higher foreign sales"],
    why: "A stronger currency helps importers and travellers and hurts exporters — the trade-off runs both ways.",
  },
  {
    id: "ec-fx-002", topic: "exchange rates", d: 2,
    q: "Under a floating exchange rate, the rate is set by",
    a: ["Supply and demand for the currency in foreign exchange markets", "The central bank's announcement", "The trade balance alone", "International agreement"],
    why: "Canada floats. A fixed regime requires the central bank to buy and sell reserves to defend the peg.",
  },
  {
    id: "ec-fx-003", topic: "exchange rates", d: 3,
    q: "Why does the Canadian dollar often move with oil prices?",
    a: ["Resource exports drive demand for the currency and shape the terms of trade", "Oil is priced in Canadian dollars", "The Bank of Canada targets the oil price", "Oil producers are required to hold loonies"],
    why: "It is a commodity currency, which is why its swings track global resource cycles.",
  },
  {
    id: "ec-think-001", topic: "economic thinkers", d: 2,
    q: "Adam Smith's 'invisible hand' describes how",
    a: ["Self-interested exchange can produce socially useful outcomes without central direction", "Governments secretly guide markets", "Prices are set by producers alone", "Charity sustains an economy"],
    why: "The Wealth of Nations appeared in 1776. Smith also wrote at length about where markets fail.",
  },
  {
    id: "ec-think-002", topic: "economic thinkers", d: 2,
    q: "Keynes argued that during a deep recession governments should",
    a: ["Spend to replace the missing private demand", "Balance the budget immediately", "Raise interest rates", "Cut wages across the board"],
    why: "His General Theory (1936) argued that economies can sit at depressed output for years without self-correcting.",
  },
  {
    id: "ec-think-003", topic: "economic thinkers", d: 2,
    q: "Milton Friedman is associated with which claim?",
    a: ["Inflation is fundamentally a monetary phenomenon", "Wages should be set by government", "Trade deficits cause recessions", "Markets never clear"],
    why: "Monetarism put the growth of the money supply at the centre and pushed back hard against Keynesian fine-tuning.",
  },
  {
    id: "ec-micro-001", topic: "micro and macro", d: 1,
    q: "Which question is microeconomic rather than macroeconomic?",
    a: ["How a bakery decides what to charge for bread", "What drives the national unemployment rate", "Why inflation accelerated last year", "How trade deficits affect the currency"],
    why: "Micro studies individual agents and markets; macro studies economy-wide aggregates.",
  },
];
