import type { SeedQuestion } from "../types";

export const general: SeedQuestion[] = [
  {
    id: "gk-space-001", topic: "space", d: 1,
    q: "Which planet is known as the Red Planet?",
    a: ["Mars", "Jupiter", "Venus", "Mercury"],
    why: "Iron oxide dust across its surface gives it the colour — rust, essentially.",
  },
  {
    id: "gk-space-002", topic: "space", d: 2,
    q: "Which planet in the Solar System is hottest at the surface?",
    a: ["Venus", "Mercury", "Mars", "Jupiter"],
    why: "Mercury is closer to the Sun, but Venus's thick carbon dioxide atmosphere traps heat relentlessly.",
    deeper: [{
      level: 3,
      q: "What does that comparison demonstrate about planetary temperature?",
      a: ["Atmosphere can matter more than distance from the star", "Rotation speed sets surface temperature", "Planet size determines heat retention", "Closer always means hotter"],
      why: "It is the clearest case in the Solar System of a greenhouse effect dominating the energy balance.",
    }],
  },
  {
    id: "gk-space-003", topic: "space", d: 1,
    q: "A light-year measures",
    a: ["Distance", "Time", "Brightness", "Mass"],
    why: "It is how far light travels in a year — about nine and a half trillion kilometres.",
  },
  {
    id: "gk-space-004", topic: "space", d: 2,
    q: "Sunlight takes roughly how long to reach Earth?",
    a: ["Eight minutes", "Eight seconds", "One hour", "Instantly"],
    why: "You always see the Sun as it was minutes ago. Nothing carries information faster than light.",
  },
  {
    id: "gk-space-005", topic: "space", d: 2,
    q: "The largest planet in the Solar System is",
    a: ["Jupiter", "Saturn", "Neptune", "Uranus"],
    why: "It holds more mass than all the other planets put together.",
  },
  {
    id: "gk-space-006", topic: "space", d: 2,
    q: "Why do astronauts float aboard the International Space Station?",
    a: ["They are in continuous free fall around the Earth", "There is no gravity at that altitude", "The station spins to cancel gravity", "They are beyond the atmosphere"],
    why: "Gravity up there is still close to 90% of its surface value. Orbiting is falling and missing the ground.",
  },
  {
    id: "gk-space-007", topic: "space", d: 2,
    q: "The first human to walk on the Moon did so in",
    a: ["1969", "1961", "1972", "1957"],
    why: "Apollo 11 landed in July. Gagarin's first human spaceflight was in 1961.",
  },
  {
    id: "gk-space-008", topic: "space", d: 3,
    q: "What makes a black hole's event horizon significant?",
    a: ["It is the boundary past which nothing, not even light, can escape", "It is the physical surface of the object", "It is where gravity becomes infinite", "It marks the edge of its magnetic field"],
    why: "It is a one-way boundary in spacetime rather than anything solid, and you would not notice crossing a large one.",
  },
  {
    id: "gk-sci-001", topic: "science", d: 1,
    q: "The powerhouse role in a cell is played by the",
    a: ["Mitochondria", "Nucleus", "Ribosome", "Cell wall"],
    why: "They produce ATP, the molecule cells actually spend, and carry their own DNA.",
  },
  {
    id: "gk-sci-002", topic: "science", d: 2,
    q: "The structure of DNA is a",
    a: ["Double helix", "Single spiral", "Branching chain", "Flat sheet"],
    why: "Franklin's X-ray diffraction images were essential evidence for the model Watson and Crick published in 1953.",
  },
  {
    id: "gk-sci-003", topic: "science", d: 2,
    q: "Photosynthesis converts light energy into",
    a: ["Chemical energy stored in sugars", "Heat", "Electricity", "Mechanical motion"],
    why: "Oxygen is the by-product, which is a fairly significant side effect for the rest of us.",
  },
  {
    id: "gk-sci-004", topic: "science", d: 2,
    q: "On the pH scale, a value below 7 means a solution is",
    a: ["Acidic", "Basic", "Neutral", "Saturated"],
    why: "The scale is logarithmic, so pH 4 is ten times more acidic than pH 5.",
  },
  {
    id: "gk-sci-005", topic: "science", d: 2,
    q: "Noble gases are chemically unreactive because their",
    a: ["Outer electron shells are already full", "Atoms are too heavy to move", "Nuclei are unstable", "Atoms carry no electrons"],
    why: "A filled shell means nothing to gain from bonding, which is why helium fills balloons that will not burn.",
  },
  {
    id: "gk-sci-006", topic: "science", d: 2,
    q: "Darwin's On the Origin of Species was published in",
    a: ["1859", "1809", "1900", "1543"],
    why: "Wallace had reached similar conclusions independently, which is part of why Darwin finally published.",
  },
  {
    id: "gk-sci-007", topic: "science", d: 3,
    q: "Mendeleev's periodic table was persuasive mainly because it",
    a: ["Predicted properties of elements not yet discovered", "Listed every known element alphabetically", "Explained the structure of the atom", "Was the first list of elements ever made"],
    why: "He left gaps and described what should fill them. When gallium and germanium turned up matching, the case was made.",
  },
  {
    id: "gk-sci-008", topic: "science", d: 2,
    q: "An atom is mostly",
    a: ["Empty space", "Solid nucleus", "Electrons by volume", "Neutral particles packed tightly"],
    why: "Rutherford's scattering experiment showed the nucleus is minute compared with the atom around it.",
  },
  {
    id: "gk-inv-001", topic: "inventions", d: 2,
    q: "The transistor was invented in 1947 at",
    a: ["Bell Labs", "IBM Research", "MIT", "Xerox PARC"],
    why: "Bardeen, Brattain and Shockley shared a Nobel for it, and essentially all modern computing followed.",
  },
  {
    id: "gk-inv-002", topic: "inventions", d: 2,
    q: "Penicillin's antibacterial effect was noticed by",
    a: ["Alexander Fleming in 1928", "Louis Pasteur", "Joseph Lister", "Robert Koch"],
    why: "Mould contaminated a culture plate. Turning that observation into a usable drug took another decade and a team at Oxford.",
  },
  {
    id: "gk-inv-003", topic: "inventions", d: 2,
    q: "The World Wide Web was proposed in 1989 by",
    a: ["Tim Berners-Lee at CERN", "Vint Cerf at DARPA", "Marc Andreessen", "Bill Gates"],
    why: "The internet already existed; the Web is the hypertext layer built on top of it.",
    deeper: [{
      level: 2,
      q: "So what is the difference between the internet and the Web?",
      a: ["The internet is the network; the Web is one service running over it", "They are the same thing", "The Web is the hardware and the internet the software", "The internet replaced the Web"],
      why: "Email, video calls and game traffic use the internet without touching the Web at all.",
    }],
  },
  {
    id: "gk-inv-004", topic: "inventions", d: 2,
    q: "X-rays were discovered by",
    a: ["Wilhelm Röntgen in 1895", "Marie Curie", "Henri Becquerel", "Ernest Rutherford"],
    why: "He called them X for unknown, and the name stuck. He won the first Nobel Prize in Physics.",
  },
  {
    id: "gk-comp-001", topic: "computing", d: 1,
    q: "A byte consists of",
    a: ["Eight bits", "Two bits", "Sixteen bits", "One character always"],
    why: "Eight bits give 256 possible values, which was enough for early character sets.",
  },
  {
    id: "gk-comp-002", topic: "computing", d: 1,
    q: "RAM is described as volatile because it",
    a: ["Loses its contents when power is removed", "Can be overwritten many times", "Runs hot under load", "Changes speed with temperature"],
    why: "That is why unsaved work disappears in a power cut and why storage and memory are different things.",
  },
  {
    id: "gk-comp-003", topic: "computing", d: 2,
    q: "What does DNS do?",
    a: ["Translates names like example.com into IP addresses", "Encrypts web traffic", "Assigns addresses to new devices", "Routes packets between networks"],
    why: "DHCP hands out addresses and routing moves packets; DNS is the directory.",
  },
  {
    id: "gk-comp-004", topic: "computing", d: 2,
    q: "In public key cryptography, what do you publish?",
    a: ["The key used to encrypt to you, keeping the decryption key private", "Both keys, so anyone can verify", "The private key, keeping the public one secret", "A shared secret agreed in advance"],
    why: "Solving key distribution without a prior shared secret is what made secure communication at internet scale possible.",
  },
  {
    id: "gk-comp-005", topic: "computing", d: 2,
    q: "Moore's law described",
    a: ["Transistor counts on a chip roughly doubling every couple of years", "Processor clock speed doubling annually", "Software growing to fill available memory", "Network bandwidth doubling every year"],
    why: "It was an observation about an industry trend, not a law of nature, and its pace has slowed.",
  },
  {
    id: "gk-comp-006", topic: "computing", d: 2,
    q: "Alan Turing is best known in computing for",
    a: ["Formalising what it means for a problem to be computable", "Building the first personal computer", "Inventing the transistor", "Founding the internet"],
    why: "The Turing machine is a model of computation, and his wartime cryptanalysis at Bletchley Park was separate work.",
  },
  {
    id: "gk-comp-007", topic: "computing", d: 3,
    q: "Ada Lovelace is credited as an early programmer because she",
    a: ["Wrote an algorithm intended for Babbage's Analytical Engine", "Built the first working computer", "Invented binary arithmetic", "Designed the first compiler"],
    why: "Her notes went further than Babbage's, suggesting the machine could manipulate symbols rather than only numbers.",
  },
  {
    id: "gk-comp-008", topic: "computing", d: 2,
    q: "What does version control software such as Git primarily give you?",
    a: ["A history of changes you can inspect, branch and revert", "Automatic backups to the cloud", "Faster compilation", "Code that cannot contain bugs"],
    why: "Branching cheaply is what lets many people work on one codebase without stepping on each other.",
  },
  {
    id: "gk-prog-001", topic: "programming", d: 2,
    q: "A recursive function is one that",
    a: ["Calls itself on a smaller version of the problem", "Runs in a loop until interrupted", "Returns more than one value", "Executes in parallel"],
    why: "It needs a base case, or it runs until the call stack is exhausted.",
  },
  {
    id: "gk-prog-002", topic: "programming", d: 2,
    q: "A compiler differs from an interpreter in that a compiler",
    a: ["Translates the whole program ahead of running it", "Executes code line by line as it reads it", "Only works on scripting languages", "Requires no source code"],
    why: "Modern runtimes blur the line, compiling hot paths at run time to get both.",
  },
  {
    id: "gk-prog-003", topic: "programming", d: 2,
    q: "Big O notation describes",
    a: ["How an algorithm's cost grows as the input grows", "Exactly how many seconds code will take", "How much memory a language uses", "The number of lines in a program"],
    why: "It is about scaling. A quadratic algorithm can beat a linear one on small inputs and lose badly on large ones.",
    deeper: [{
      level: 3,
      q: "Why then does an O(n log n) sort sometimes lose to an O(n²) sort in practice?",
      a: ["On small inputs, constant factors and memory locality dominate the growth rate", "Big O is usually calculated wrongly", "Quadratic algorithms use less memory by definition", "Growth rate only applies to recursive code"],
      why: "This is why real sort implementations switch to insertion sort below a size threshold.",
    }],
  },
  {
    id: "gk-prog-004", topic: "programming", d: 2,
    q: "The term 'bug' for a computer fault was popularised by an incident involving",
    a: ["A moth found in a relay of the Harvard Mark II", "A mistranslated German term", "A programmer named Bugg", "A faulty vacuum tube nickname"],
    why: "Grace Hopper's team taped it into the logbook. Engineers had used 'bug' for faults long before, which is why the note was funny.",
  },
  {
    id: "gk-lit-001", topic: "literature", d: 1,
    q: "Nineteen Eighty-Four was written by",
    a: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "H. G. Wells"],
    why: "Published in 1949. Huxley's Brave New World imagines control through pleasure rather than fear.",
  },
  {
    id: "gk-lit-002", topic: "literature", d: 2,
    q: "The Odyssey and the Iliad are attributed to",
    a: ["Homer", "Virgil", "Sophocles", "Ovid"],
    why: "Whether one poet wrote them, or whether Homer existed at all, is still argued.",
  },
  {
    id: "gk-lit-003", topic: "literature", d: 2,
    q: "Don Quixote was written by",
    a: ["Miguel de Cervantes", "Lope de Vega", "Dante Alighieri", "Gabriel García Márquez"],
    why: "Published in two parts, 1605 and 1615, and often called the first modern novel.",
  },
  {
    id: "gk-lit-004", topic: "literature", d: 2,
    q: "Pride and Prejudice was written by",
    a: ["Jane Austen", "Charlotte Brontë", "George Eliot", "Elizabeth Gaskell"],
    why: "Published anonymously in 1813 — her novels appeared as 'By a Lady' in her lifetime.",
  },
  {
    id: "gk-lit-005", topic: "literature", d: 2,
    q: "A sonnet has how many lines?",
    a: ["Fourteen", "Twelve", "Sixteen", "Eight"],
    why: "Shakespearean sonnets close with a rhyming couplet; Petrarchan ones break eight lines against six.",
  },
  {
    id: "gk-lang-001", topic: "languages", d: 2,
    q: "Which language has the most native speakers?",
    a: ["Mandarin Chinese", "English", "Spanish", "Hindi"],
    why: "English leads once second-language speakers are counted, which is a different ranking.",
  },
  {
    id: "gk-lang-002", topic: "languages", d: 2,
    q: "Spanish, French, Italian, Portuguese and Romanian are all",
    a: ["Romance languages descended from Latin", "Germanic languages", "Slavic languages", "Unrelated to each other"],
    why: "They grew out of the spoken Latin of different Roman provinces.",
  },
  {
    id: "gk-lang-003", topic: "languages", d: 3,
    q: "Esperanto is unusual among widely known languages because it",
    a: ["Was deliberately constructed rather than evolved", "Has no written form", "Uses no verbs", "Is spoken only in one country"],
    why: "Zamenhof designed it in the 1880s as a politically neutral second language.",
  },
  {
    id: "gk-ppl-001", topic: "famous people", d: 2,
    q: "Marie Curie is unique among Nobel laureates for having won",
    a: ["Prizes in two different sciences", "Three prizes in physics", "The first prize ever awarded", "A prize she later refused"],
    why: "Physics in 1903 and chemistry in 1911. She remains the only person to win in two scientific fields.",
  },
  {
    id: "gk-ppl-002", topic: "famous people", d: 2,
    q: "Nelson Mandela became president of South Africa in",
    a: ["1994", "1990", "1999", "1986"],
    why: "He was released from prison in 1990; the first fully democratic election came four years later.",
  },
  {
    id: "gk-ppl-003", topic: "famous people", d: 2,
    q: "Nikola Tesla's key contribution to electrical power was",
    a: ["Championing alternating current systems", "Inventing the battery", "Discovering electromagnetic induction", "Building the first power station"],
    why: "AC transforms easily to high voltage, which is what makes long-distance transmission practical.",
  },
  {
    id: "gk-ppl-004", topic: "famous people", d: 2,
    q: "Which of these did Einstein receive his Nobel Prize for?",
    a: ["The photoelectric effect", "Special relativity", "General relativity", "The equivalence of mass and energy"],
    why: "Relativity was still contested in 1921; the photoelectric work was solid, and it helped found quantum theory.",
  },
  {
    id: "gk-world-001", topic: "world facts", d: 2,
    q: "The United Nations was founded in",
    a: ["1945", "1919", "1950", "1939"],
    why: "It replaced the League of Nations, which had failed to prevent a second world war.",
  },
  {
    id: "gk-world-002", topic: "world facts", d: 2,
    q: "How many permanent members hold a veto on the UN Security Council?",
    a: ["Five", "Three", "Ten", "Fifteen"],
    why: "The victorious powers of 1945 — a structure that has barely changed since.",
  },
  {
    id: "gk-world-003", topic: "world facts", d: 2,
    q: "A leap year adds a day because",
    a: ["Earth's orbit takes about a quarter day more than 365 days", "The Moon's cycle needs correcting", "Calendars drift through rounding errors", "Earth's rotation is slowing"],
    why: "The extra quarter-day accumulates, and the century rule trims the remaining small overcorrection.",
  },
  {
    id: "gk-world-004", topic: "world facts", d: 2,
    q: "The euro is the official currency of",
    a: ["Most, but not all, European Union members", "Every European country", "Every European Union member", "Only the founding EU members"],
    why: "Sweden and Poland, among others, keep their own currencies. Some non-EU states use the euro anyway.",
  },
  {
    id: "gk-tech-001", topic: "technology", d: 2,
    q: "Why does a lithium-ion battery lose capacity as it ages?",
    a: ["Chemical side reactions permanently consume usable lithium and electrode material", "It develops a memory of shallow charges", "Its voltage rating drifts upward", "Heat evaporates the electrolyte instantly"],
    why: "Memory effect belonged to older nickel-cadmium cells. Heat and time at high state of charge accelerate lithium ageing.",
  },
  {
    id: "gk-tech-002", topic: "technology", d: 2,
    q: "A microwave oven heats food by",
    a: ["Making water molecules rotate rapidly", "Emitting infrared radiation", "Ionising the food's molecules", "Conducting heat from the walls"],
    why: "Microwaves are far too low in energy to ionise anything. Dry food with little water heats poorly.",
  },
  {
    id: "gk-tech-003", topic: "technology", d: 2,
    q: "Fibre optic cable carries data as",
    a: ["Pulses of light guided by total internal reflection", "Electrical pulses in a glass conductor", "Radio waves inside a tube", "Magnetic pulses along a core"],
    why: "Glass loses far less signal per kilometre than copper and is immune to electrical interference.",
  },
];
