import type { SeedQuestion } from "../types";

export const geography: SeedQuestion[] = [
  {
    id: "ge-cap-001", topic: "capitals", d: 1,
    q: "The capital of Australia is",
    a: ["Canberra", "Sydney", "Melbourne", "Perth"],
    why: "It was purpose-built as a compromise between Sydney and Melbourne, which both wanted the job.",
  },
  {
    id: "ge-cap-002", topic: "capitals", d: 2,
    q: "The capital of Brazil is",
    a: ["Brasília", "Rio de Janeiro", "São Paulo", "Salvador"],
    why: "Built inland in the 1950s to pull development away from the crowded coast.",
  },
  {
    id: "ge-cap-003", topic: "capitals", d: 2,
    q: "The capital of Turkey is",
    a: ["Ankara", "Istanbul", "Izmir", "Bursa"],
    why: "Istanbul is much larger, but Atatürk moved the seat of government to Ankara in 1923.",
  },
  {
    id: "ge-cap-004", topic: "capitals", d: 2,
    q: "The capital of Switzerland is",
    a: ["Bern", "Zurich", "Geneva", "Basel"],
    why: "Switzerland calls it a federal city rather than a capital, but it is where the government sits.",
  },
  {
    id: "ge-cap-005", topic: "capitals", d: 2,
    q: "The capital of New Zealand is",
    a: ["Wellington", "Auckland", "Christchurch", "Dunedin"],
    why: "Auckland is bigger; Wellington sits closer to the country's geographic centre.",
  },
  {
    id: "ge-cap-006", topic: "capitals", d: 3,
    q: "The capital of Kazakhstan is",
    a: ["Astana", "Almaty", "Karaganda", "Shymkent"],
    why: "The capital moved from Almaty in 1997, and the city's name has changed more than once since.",
  },
  {
    id: "ge-cap-007", topic: "capitals", d: 2,
    q: "The capital of Morocco is",
    a: ["Rabat", "Casablanca", "Marrakesh", "Fez"],
    why: "Casablanca is the economic centre, but Rabat holds the government.",
  },
  {
    id: "ge-cap-008", topic: "capitals", d: 3,
    q: "Which country has three capital cities, each holding a different branch of government?",
    a: ["South Africa", "Bolivia", "Chile", "Malaysia"],
    why: "Pretoria is executive, Cape Town legislative, Bloemfontein judicial — a compromise from the 1910 union.",
  },
  {
    id: "ge-ctry-001", topic: "countries", d: 1,
    q: "The largest country by land area is",
    a: ["Russia", "Canada", "China", "The United States"],
    why: "It spans eleven time zones, and Canada is second by area.",
  },
  {
    id: "ge-ctry-002", topic: "countries", d: 2,
    q: "Which two countries each share land borders with fourteen neighbours, more than any others?",
    a: ["China and Russia", "Brazil and India", "Germany and Turkey", "Sudan and Kazakhstan"],
    why: "Brazil leads South America with ten.",
  },
  {
    id: "ge-ctry-003", topic: "countries", d: 2,
    q: "Which country lies on both the European and Asian sides of a strait running through its largest city?",
    a: ["Turkey", "Greece", "Egypt", "Russia"],
    why: "The Bosphorus splits Istanbul between two continents.",
  },
  {
    id: "ge-ctry-004", topic: "countries", d: 2,
    q: "Which South American country is landlocked?",
    a: ["Bolivia", "Peru", "Ecuador", "Venezuela"],
    why: "Bolivia and Paraguay are the continent's two. Bolivia lost its coast to Chile in the nineteenth century.",
  },
  {
    id: "ge-ctry-005", topic: "countries", d: 3,
    q: "A doubly landlocked country is one whose neighbours are all landlocked too. Which is one?",
    a: ["Uzbekistan", "Mongolia", "Nepal", "Austria"],
    why: "Liechtenstein is the only other one. You must cross at least two borders to reach an ocean.",
  },
  {
    id: "ge-ctry-006", topic: "countries", d: 2,
    q: "Which country is entirely surrounded by South Africa?",
    a: ["Lesotho", "Eswatini", "Botswana", "Namibia"],
    why: "Eswatini borders Mozambique as well, so Lesotho is the true enclave.",
  },
  {
    id: "ge-flag-001", topic: "flags", d: 2,
    q: "Which country has the only national flag that is not a rectangle?",
    a: ["Nepal", "Switzerland", "Vatican City", "Bhutan"],
    why: "Two stacked pennants. Switzerland's flag is square, which is unusual but still four-sided.",
  },
  {
    id: "ge-flag-002", topic: "flags", d: 2,
    q: "A plain red circle centred on white is the flag of",
    a: ["Japan", "Bangladesh", "Palau", "Tunisia"],
    why: "Bangladesh uses a red disc offset on green, and Palau a yellow disc on blue.",
  },
  {
    id: "ge-flag-003", topic: "flags", d: 2,
    q: "The Canadian flag in its current form was adopted in",
    a: ["1965", "1867", "1931", "1982"],
    why: "The Great Flag Debate was fierce; the maple leaf replaced the Red Ensign.",
  },
  {
    id: "ge-cont-001", topic: "continents and oceans", d: 1,
    q: "The largest ocean is the",
    a: ["Pacific", "Atlantic", "Indian", "Southern"],
    why: "It covers roughly a third of the planet's surface — more than all land combined.",
  },
  {
    id: "ge-cont-002", topic: "continents and oceans", d: 2,
    q: "The deepest known point in the ocean lies in the",
    a: ["Mariana Trench", "Puerto Rico Trench", "Java Trench", "Tonga Trench"],
    why: "Challenger Deep is close to eleven kilometres down — deeper than Everest is tall.",
  },
  {
    id: "ge-cont-003", topic: "continents and oceans", d: 2,
    q: "By area, the world's largest desert is",
    a: ["Antarctica", "The Sahara", "The Arabian", "The Gobi"],
    why: "A desert is defined by low precipitation, not heat. Antarctica is the driest continent.",
    deeper: [{
      level: 2,
      q: "Given that definition, which is the largest hot desert?",
      a: ["The Sahara", "The Gobi", "The Kalahari", "The Atacama"],
      why: "It spans most of northern Africa and is roughly the size of the United States.",
    }],
  },
  {
    id: "ge-cont-004", topic: "continents and oceans", d: 2,
    q: "Which continent has the most countries?",
    a: ["Africa", "Asia", "Europe", "South America"],
    why: "Fifty-four, a legacy of how colonial borders were drawn and then inherited at independence.",
  },
  {
    id: "ge-mtn-001", topic: "mountains", d: 1,
    q: "The highest mountain above sea level is",
    a: ["Everest", "K2", "Denali", "Aconcagua"],
    why: "Just under 8,850 metres, on the Nepal–China border.",
  },
  {
    id: "ge-mtn-002", topic: "mountains", d: 2,
    q: "The world's longest mountain range on land is the",
    a: ["Andes", "Himalayas", "Rockies", "Alps"],
    why: "About 7,000 kilometres down the western edge of South America.",
  },
  {
    id: "ge-mtn-003", topic: "mountains", d: 2,
    q: "The highest peak in Africa is",
    a: ["Kilimanjaro", "Mount Kenya", "The Atlas", "Ras Dashen"],
    why: "A dormant volcano in Tanzania, high enough to carry glaciers almost on the equator.",
  },
  {
    id: "ge-mtn-004", topic: "mountains", d: 3,
    q: "Which mountain range is conventionally used to divide Europe from Asia?",
    a: ["The Urals", "The Caucasus", "The Carpathians", "The Alps"],
    why: "The division is a cultural convention rather than a geological one — the two are one landmass.",
  },
  {
    id: "ge-riv-001", topic: "rivers", d: 2,
    q: "Which river discharges by far the most water into the ocean?",
    a: ["The Amazon", "The Nile", "The Congo", "The Yangtze"],
    why: "It carries about a fifth of all river water reaching the sea, more than the next several combined.",
  },
  {
    id: "ge-riv-002", topic: "rivers", d: 2,
    q: "The longest river in Asia is the",
    a: ["Yangtze", "Mekong", "Ganges", "Ob"],
    why: "It runs right across China and has been a transport artery for millennia.",
  },
  {
    id: "ge-riv-003", topic: "rivers", d: 2,
    q: "The longest river in Europe is the",
    a: ["Volga", "Danube", "Rhine", "Loire"],
    why: "It flows entirely within Russia and empties into the Caspian Sea.",
  },
  {
    id: "ge-riv-004", topic: "rivers", d: 2,
    q: "Which river flows through the most countries?",
    a: ["The Danube", "The Rhine", "The Nile", "The Mekong"],
    why: "Ten countries, from Germany's Black Forest to the Black Sea.",
  },
  {
    id: "ge-riv-005", topic: "rivers", d: 2,
    q: "The Nile empties into the",
    a: ["Mediterranean Sea", "Red Sea", "Indian Ocean", "Gulf of Aden"],
    why: "Its delta north of Cairo is one of the most densely farmed places on Earth.",
  },
  {
    id: "ge-phys-001", topic: "physical geography", d: 2,
    q: "The largest lake by surface area on Earth is the",
    a: ["Caspian Sea", "Lake Superior", "Lake Victoria", "Lake Baikal"],
    why: "Despite the name it is a lake — saline and endorheic, with no outlet to an ocean.",
  },
  {
    id: "ge-phys-002", topic: "physical geography", d: 3,
    q: "Lake Baikal holds more liquid fresh water than any other lake because it is",
    a: ["Extraordinarily deep, in a continental rift", "Larger in area than any other", "Fed by more rivers than any other", "Frozen for most of the year"],
    why: "Over 1,600 metres deep. Area and volume rankings are different questions.",
  },
  {
    id: "ge-phys-003", topic: "physical geography", d: 2,
    q: "Earthquakes and volcanoes cluster around the Pacific because",
    a: ["Tectonic plate boundaries ring the ocean basin", "The ocean's weight cracks the crust", "The Pacific is the oldest ocean floor", "Ocean currents heat the seabed"],
    why: "Subduction zones along the Ring of Fire do most of the work.",
  },
  {
    id: "ge-phys-004", topic: "physical geography", d: 2,
    q: "A rain shadow forms when",
    a: ["Air loses its moisture rising over a range, leaving the far side dry", "A desert reflects sunlight onto a mountain", "Cold ocean water suppresses rainfall inland", "Forests block prevailing winds"],
    why: "It explains why one side of a range can be rainforest and the other near-desert.",
  },
  {
    id: "ge-phys-005", topic: "physical geography", d: 2,
    q: "Which of these best explains why Britain is milder than Newfoundland at the same latitude?",
    a: ["Warm ocean currents carry heat north-east across the Atlantic", "Britain is closer to the equator", "Prevailing winds come from the Arctic in Newfoundland only", "Britain sits at a lower elevation"],
    why: "The North Atlantic Drift moves an enormous amount of heat toward north-west Europe.",
  },
  {
    id: "ge-phys-006", topic: "physical geography", d: 2,
    q: "The Panama Canal connects",
    a: ["The Atlantic and Pacific Oceans", "The Mediterranean and the Red Sea", "The Black Sea and the Aegean", "The Caribbean and the Gulf of Mexico"],
    why: "The Suez Canal is the one joining the Mediterranean to the Red Sea.",
  },
  {
    id: "ge-hum-001", topic: "human geography", d: 2,
    q: "Urbanisation refers to",
    a: ["A rising share of a population living in cities", "Total population growth", "Cities expanding outward in area", "Migration between countries"],
    why: "Sprawl is a separate idea, and a country can urbanise while its total population falls.",
  },
  {
    id: "ge-hum-002", topic: "human geography", d: 3,
    q: "In the demographic transition model, population grows fastest in the stage where",
    a: ["Death rates have fallen but birth rates are still high", "Both rates are high", "Both rates are low", "Birth rates fall below death rates"],
    why: "The gap between the two curves is the growth, and it is widest during that lag.",
  },
  {
    id: "ge-hum-003", topic: "human geography", d: 2,
    q: "Canada's population is heavily concentrated",
    a: ["Within a few hundred kilometres of the United States border", "Along the Arctic coast", "In the Prairie interior", "Evenly across all provinces"],
    why: "Climate, farmland and trade links all pull settlement south.",
  },
  {
    id: "ge-hum-004", topic: "human geography", d: 2,
    q: "Which country has the world's largest population?",
    a: ["India", "China", "The United States", "Indonesia"],
    why: "India passed China in 2023, and the two together are over a third of humanity.",
  },
  {
    id: "ge-map-001", topic: "maps", d: 2,
    q: "The Mercator projection is criticised because it",
    a: ["Badly exaggerates the size of land near the poles", "Distorts direction, making navigation hard", "Cannot show the oceans", "Shows the Earth as flat-topped"],
    why: "It preserves angles, which is exactly what made it useful for sailing. Greenland is the famous casualty.",
    deeper: [{
      level: 3,
      q: "Why can no flat map preserve both shape and area everywhere?",
      a: ["A sphere's surface cannot be flattened without stretching or tearing", "Printing limits resolution", "The Earth is not a perfect sphere", "Longitude lines are not parallel"],
      why: "Every projection chooses what to sacrifice. The right map depends on the job.",
    }],
  },
  {
    id: "ge-map-002", topic: "maps", d: 2,
    q: "Lines of latitude",
    a: ["Run parallel to the equator and never meet", "Converge at the poles", "Measure distance east and west", "Are the same as meridians"],
    why: "Longitude lines are the ones that converge, which is why degrees of longitude shrink as you go north.",
  },
  {
    id: "ge-map-003", topic: "maps", d: 2,
    q: "On a topographic map, closely spaced contour lines indicate",
    a: ["Steep ground", "Flat ground", "Water", "Dense forest"],
    why: "Each line is a fixed height interval, so tight spacing means you climb that interval over a short distance.",
  },
  {
    id: "ge-map-004", topic: "maps", d: 2,
    q: "The prime meridian passes through",
    a: ["Greenwich, in London", "Paris", "The Canary Islands", "Rome"],
    why: "Agreed internationally in 1884 largely because most shipping charts already used it.",
  },
  {
    id: "ge-cit-001", topic: "cities and borders", d: 2,
    q: "Which of these cities is furthest north?",
    a: ["Oslo", "Toronto", "Beijing", "Madrid"],
    why: "Much of northern Europe lies well above Canada's populated south, which the Atlantic's warmth makes liveable.",
  },
  {
    id: "ge-cit-002", topic: "cities and borders", d: 2,
    q: "The world's longest international border runs between",
    a: ["Canada and the United States", "Russia and Kazakhstan", "Chile and Argentina", "China and Mongolia"],
    why: "Nearly 9,000 kilometres, including the Alaska boundary.",
  },
  {
    id: "ge-cit-003", topic: "cities and borders", d: 2,
    q: "Which city sits on the Bosphorus?",
    a: ["Istanbul", "Athens", "Odesa", "Alexandria"],
    why: "It commands the only sea route between the Black Sea and the Mediterranean.",
  },
  {
    id: "ge-cit-004", topic: "cities and borders", d: 3,
    q: "Nunavut, Canada's newest territory, was created in",
    a: ["1999", "1982", "1949", "1905"],
    why: "It was separated from the Northwest Territories following a land claims agreement with the Inuit.",
  },
  {
    id: "ge-cit-005", topic: "cities and borders", d: 2,
    q: "Which country has the world's longest coastline?",
    a: ["Canada", "Russia", "Indonesia", "Australia"],
    why: "The Arctic archipelago's countless islands make the total enormous.",
  },
];
