import type { SeedQuestion } from "../types";

export const history: SeedQuestion[] = [
  {
    id: "hi-anc-001", topic: "ancient world", d: 1,
    q: "Which city-state is credited with the earliest form of direct democracy?",
    a: ["Athens", "Sparta", "Corinth", "Thebes"],
    why: "Citizens voted in person on legislation, though citizenship excluded women, slaves and foreigners.",
  },
  {
    id: "hi-anc-002", topic: "ancient world", d: 2,
    q: "Alexander the Great was tutored as a boy by",
    a: ["Aristotle", "Plato", "Socrates", "Archimedes"],
    why: "Philip II hired Aristotle for his son. Alexander carried Greek culture as far as the Indus.",
  },
  {
    id: "hi-anc-003", topic: "ancient world", d: 2,
    q: "Rome's great rival in the Punic Wars was",
    a: ["Carthage", "Persia", "Macedon", "Egypt"],
    why: "Three wars ended with Carthage destroyed in 146 BC, leaving Rome dominant in the western Mediterranean.",
  },
  {
    id: "hi-anc-004", topic: "ancient world", d: 2,
    q: "Julius Caesar was assassinated in which year?",
    a: ["44 BC", "27 BC", "14 AD", "79 AD"],
    why: "The conspirators hoped to save the Republic. Within two decades Augustus had ended it.",
  },
  {
    id: "hi-anc-005", topic: "ancient world", d: 2,
    q: "Who became the first Roman emperor?",
    a: ["Augustus", "Julius Caesar", "Nero", "Constantine"],
    why: "Octavian took the name Augustus in 27 BC and ruled while carefully preserving republican forms.",
  },
  {
    id: "hi-anc-006", topic: "ancient world", d: 2,
    q: "The Code of Hammurabi comes from which civilisation?",
    a: ["Babylon", "Ancient Egypt", "The Hittites", "Assyria"],
    why: "One of the earliest surviving written legal codes, carved on a stone stele around 1750 BC.",
  },
  {
    id: "hi-anc-007", topic: "ancient world", d: 2,
    q: "The Western Roman Empire is conventionally dated as falling in",
    a: ["476 AD", "410 AD", "395 AD", "1453 AD"],
    why: "The last western emperor was deposed that year. The eastern half carried on for another thousand years.",
    deeper: [{
      level: 3,
      q: "Why do many historians resist calling 476 a 'fall' at all?",
      a: ["Roman institutions, law and language continued under new rulers for generations", "The date is simply wrong by a century", "No emperor was actually deposed", "Rome was never conquered"],
      why: "Transformation rather than collapse: the change was gradual, regional and far less abrupt than the date suggests.",
    }],
  },
  {
    id: "hi-med-001", topic: "medieval world", d: 1,
    q: "The Battle of Hastings took place in",
    a: ["1066", "1215", "1348", "911"],
    why: "William of Normandy's victory reshaped English land ownership, law and language.",
  },
  {
    id: "hi-med-002", topic: "medieval world", d: 2,
    q: "Magna Carta, sealed in 1215, mattered because it",
    a: ["Established that the king was subject to law", "Abolished feudalism", "Created Parliament", "Granted rights to peasants"],
    why: "It was a bargain with rebellious barons, but the principle of a limited crown outlived its original terms.",
  },
  {
    id: "hi-med-003", topic: "medieval world", d: 2,
    q: "Charlemagne was crowned Emperor of the Romans in the year",
    a: ["800", "1066", "962", "476"],
    why: "Pope Leo III crowned him on Christmas Day, linking papal authority to a revived western empire.",
  },
  {
    id: "hi-med-004", topic: "medieval world", d: 2,
    q: "The First Crusade was launched after a call by",
    a: ["Pope Urban II in 1095", "Richard the Lionheart", "Charlemagne", "Emperor Constantine"],
    why: "His appeal at Clermont drew on a Byzantine request for help against the Seljuk Turks.",
  },
  {
    id: "hi-med-005", topic: "medieval world", d: 3,
    q: "Beyond the death toll, why did the Black Death reshape European society?",
    a: ["Labour scarcity raised wages and weakened serfdom", "It ended all long-distance trade permanently", "It caused the Reformation directly", "It emptied the cities for a century"],
    why: "Survivors could bargain. Landlords who once commanded labour now had to compete for it.",
  },
  {
    id: "hi-med-006", topic: "medieval world", d: 2,
    q: "Constantinople fell to the Ottomans in",
    a: ["1453", "1204", "1517", "1389"],
    why: "Mehmed II's cannons ended the Byzantine Empire, and the date is often used to close the Middle Ages.",
  },
  {
    id: "hi-ren-001", topic: "Renaissance", d: 2,
    q: "The Italian Renaissance began in which city?",
    a: ["Florence", "Rome", "Venice", "Milan"],
    why: "Banking wealth, notably the Medici, paid for the artists and scholars who defined the period.",
  },
  {
    id: "hi-ren-002", topic: "Renaissance", d: 2,
    q: "Renaissance humanism placed new emphasis on",
    a: ["Human potential and the study of classical texts", "Monastic withdrawal from the world", "Rejecting all ancient authors", "Feudal loyalty"],
    why: "Scholars went back to Greek and Roman sources directly rather than through medieval commentary.",
  },
  {
    id: "hi-ren-003", topic: "Renaissance", d: 2,
    q: "Gutenberg's printing press, developed around 1440, mattered most because it",
    a: ["Made copies cheap, so ideas spread faster than authorities could control them", "Invented paper", "Was the first use of written language in Europe", "Was reserved for religious texts"],
    why: "Luther's pamphlets a lifetime later reached tens of thousands within weeks — unthinkable in a manuscript age.",
    deeper: [{
      level: 3,
      q: "Which later movement depended most directly on that printing capacity?",
      a: ["The Protestant Reformation", "The Crusades", "The fall of Constantinople", "The Norman Conquest"],
      why: "Cheap vernacular Bibles and pamphlets let reformers bypass the Church's control of the written word.",
    }],
  },
  {
    id: "hi-ref-001", topic: "Reformation", d: 1,
    q: "Martin Luther's Ninety-five Theses date from",
    a: ["1517", "1492", "1453", "1648"],
    why: "His objection centred on indulgences, but the challenge quickly widened to papal authority itself.",
  },
  {
    id: "hi-ref-002", topic: "Reformation", d: 2,
    q: "Henry VIII broke with Rome primarily to",
    a: ["Annul his marriage and gain control of the English church", "Adopt Lutheran theology", "Escape a Spanish invasion", "Fund a crusade"],
    why: "The break was political and dynastic first; England's theology shifted later, under Edward VI and Elizabeth I.",
  },
  {
    id: "hi-ref-003", topic: "Reformation", d: 2,
    q: "The Peace of Westphalia in 1648 is remembered for",
    a: ["Ending the Thirty Years' War and entrenching state sovereignty", "Beginning the Reformation", "Uniting Germany", "Establishing the papacy's authority over kings"],
    why: "Rulers settled their own state's religion, and the treaty became a founding reference for the modern state system.",
  },
  {
    id: "hi-exp-001", topic: "exploration", d: 1,
    q: "Columbus's first westward voyage took place in",
    a: ["1492", "1498", "1519", "1607"],
    why: "He was looking for a route to Asia and died still insisting he had found its edge.",
  },
  {
    id: "hi-exp-002", topic: "exploration", d: 2,
    q: "The first expedition to circumnavigate the globe returned in 1522 under",
    a: ["Elcano, after Magellan was killed en route", "Magellan himself", "Vasco da Gama", "Francis Drake"],
    why: "One ship of five made it home. Magellan died in the Philippines partway through.",
  },
  {
    id: "hi-exp-003", topic: "exploration", d: 2,
    q: "Jacques Cartier is known in Canadian history for",
    a: ["Claiming the St Lawrence region for France in the 1530s", "Founding Quebec City", "Discovering Hudson Bay", "Mapping the Pacific coast"],
    why: "Samuel de Champlain founded Quebec later, in 1608, building on Cartier's claims.",
  },
  {
    id: "hi-exp-004", topic: "exploration", d: 3,
    q: "What made European long-distance voyages practical in the fifteenth century?",
    a: ["Better ship design, the magnetic compass and improved navigation together", "The steam engine", "Accurate marine chronometers", "State-funded weather forecasting"],
    why: "The caravel, the compass and celestial navigation combined. Longitude stayed unsolved until the 1700s.",
  },
  {
    id: "hi-sci-001", topic: "Scientific Revolution", d: 2,
    q: "Copernicus's model of the heavens placed at the centre",
    a: ["The Sun", "The Earth", "The Moon", "A point of empty space"],
    why: "Heliocentrism was published in 1543. The observational case only became overwhelming later.",
  },
  {
    id: "hi-sci-002", topic: "Scientific Revolution", d: 2,
    q: "Galileo's telescope observations of Jupiter's moons mattered because they showed",
    a: ["Not everything orbits the Earth", "The Sun is a star", "The Earth is round", "Planets shine by their own light"],
    why: "Four moons circling another body broke the assumption that Earth was the sole centre of motion.",
  },
  {
    id: "hi-sci-003", topic: "Scientific Revolution", d: 2,
    q: "Newton's Principia, published in 1687, unified",
    a: ["Motion on Earth and in the heavens under one set of laws", "Electricity and magnetism", "Chemistry and physics", "Optics and thermodynamics"],
    why: "The same gravity that drops an apple holds the Moon in orbit — an astonishing claim at the time.",
  },
  {
    id: "hi-enl-001", topic: "Enlightenment", d: 2,
    q: "Montesquieu is best known for arguing for",
    a: ["Separation of government powers into branches", "Absolute monarchy", "The general will", "Free trade between nations"],
    why: "His analysis shaped the American constitutional structure directly.",
  },
  {
    id: "hi-enl-002", topic: "Enlightenment", d: 2,
    q: "John Locke argued that legitimate government rests on",
    a: ["The consent of the governed, who keep natural rights", "Divine right of kings", "Military strength", "Inherited aristocratic duty"],
    why: "Life, liberty and property — language that echoes straight through the American Declaration.",
  },
  {
    id: "hi-enl-003", topic: "Enlightenment", d: 3,
    q: "Rousseau's 'general will' differs from simple majority rule in that it refers to",
    a: ["What serves the common good of the whole community", "Whatever the largest faction wants", "The monarch's judgement", "Unanimous agreement on every law"],
    why: "The ambiguity has been read both as deep democracy and as a justification for coercion in the people's name.",
  },
  {
    id: "hi-rev-001", topic: "revolutions", d: 1,
    q: "The storming of the Bastille took place in",
    a: ["1789", "1776", "1799", "1815"],
    why: "A handful of prisoners were inside. The symbolism of the fortress falling was what mattered.",
  },
  {
    id: "hi-rev-002", topic: "revolutions", d: 2,
    q: "Napoleon's final defeat came at",
    a: ["Waterloo in 1815", "Leipzig in 1813", "Trafalgar in 1805", "Austerlitz in 1805"],
    why: "He was exiled to Saint Helena and died there in 1821.",
  },
  {
    id: "hi-rev-003", topic: "revolutions", d: 3,
    q: "The Haitian Revolution is distinctive because it",
    a: ["Produced the first state founded by a successful slave revolt", "Was led by French aristocrats", "Failed and restored colonial rule", "Ended without any fighting"],
    why: "Independence came in 1804, and the new republic was diplomatically isolated and financially punished for decades.",
  },
  {
    id: "hi-ind-001", topic: "Industrial Revolution", d: 2,
    q: "The Industrial Revolution began in",
    a: ["Britain in the late eighteenth century", "France after 1789", "Germany in the 1850s", "The United States after 1800"],
    why: "Coal, colonial markets, capital and a patent system converged there first.",
  },
  {
    id: "hi-ind-002", topic: "Industrial Revolution", d: 2,
    q: "James Watt's contribution was to",
    a: ["Greatly improve the efficiency of the steam engine", "Invent the steam engine outright", "Build the first railway", "Discover coal gas"],
    why: "The separate condenser cut fuel use enough to make steam power viable far from coalfields.",
  },
  {
    id: "hi-ind-003", topic: "Industrial Revolution", d: 2,
    q: "The clearest social consequence of industrialisation was",
    a: ["Rapid urbanisation as people moved to factory towns", "A decline in total population", "The end of child labour", "A return to rural crafts"],
    why: "Cities grew faster than sanitation or housing could follow, which is why public health reform became urgent.",
  },
  {
    id: "hi-ca-001", topic: "Canada", d: 1,
    q: "Canadian Confederation took effect on",
    a: ["1 July 1867", "1 July 1841", "11 December 1931", "17 April 1982"],
    why: "The British North America Act joined Ontario, Quebec, Nova Scotia and New Brunswick.",
  },
  {
    id: "hi-ca-002", topic: "Canada", d: 2,
    q: "Canada's first prime minister was",
    a: ["John A. Macdonald", "Wilfrid Laurier", "George-Étienne Cartier", "Alexander Mackenzie"],
    why: "He led the Confederation project and the drive to build a transcontinental railway.",
  },
  {
    id: "hi-ca-003", topic: "Canada", d: 2,
    q: "The Battle of Vimy Ridge in 1917 is remembered in Canada because",
    a: ["All four Canadian divisions fought together and took a position others had failed to hold", "It ended the First World War", "It was Canada's first naval victory", "It was fought on Canadian soil"],
    why: "The victory came at heavy cost and became a touchstone for a distinct national identity.",
  },
  {
    id: "hi-ca-004", topic: "Canada", d: 3,
    q: "What did the Statute of Westminster, 1931, do?",
    a: ["Gave Dominions full legal control over their own foreign and domestic policy", "Created Canadian Confederation", "Patriated the constitution", "Established the Supreme Court of Canada"],
    why: "Constitutional amendment still required Britain, which is what patriation in 1982 finally resolved.",
    deeper: [{
      level: 3,
      q: "What did the Constitution Act, 1982, add that most changed daily law in Canada?",
      a: ["The Charter of Rights and Freedoms, enforceable in court", "A new national anthem", "Provincial legislatures", "Membership in the Commonwealth"],
      why: "Courts could now strike down legislation that violated entrenched rights — a considerable shift in power.",
    }],
  },
  {
    id: "hi-ww1-001", topic: "First World War", d: 1,
    q: "The event that triggered the July Crisis of 1914 was the assassination of",
    a: ["Archduke Franz Ferdinand in Sarajevo", "Tsar Nicholas II", "Kaiser Wilhelm II's brother", "The King of Serbia"],
    why: "The alliance system turned a regional quarrel into a continental war within six weeks.",
  },
  {
    id: "hi-ww1-002", topic: "First World War", d: 2,
    q: "Why did the Western Front settle into trench warfare?",
    a: ["Machine guns and artillery made defence far cheaper than attack", "Neither side had enough soldiers", "Generals agreed to avoid open battle", "The terrain made movement impossible"],
    why: "Firepower had outrun mobility. Tanks, aircraft and new tactics only broke the deadlock late in the war.",
  },
  {
    id: "hi-ww1-003", topic: "First World War", d: 2,
    q: "Russia left the war in 1918 because",
    a: ["The Bolsheviks took power and signed a separate peace", "It had defeated Germany in the east", "Its allies demanded it", "Its army was never committed"],
    why: "The Treaty of Brest-Litovsk cost enormous territory, but the new government needed to survive at home.",
  },
  {
    id: "hi-ww1-004", topic: "First World War", d: 2,
    q: "The Treaty of Versailles is most criticised for",
    a: ["Imposing terms on Germany that fed later resentment", "Being too lenient to the victors", "Ignoring France's security concerns", "Creating no international body at all"],
    why: "The war-guilt clause and reparations were politically explosive, though historians still debate how decisive they were.",
  },
  {
    id: "hi-ww2-001", topic: "Second World War", d: 1,
    q: "The war in Europe began with Germany's invasion of",
    a: ["Poland in September 1939", "France in 1940", "Czechoslovakia in 1938", "The Soviet Union in 1941"],
    why: "Britain and France had guaranteed Polish independence and declared war two days later.",
  },
  {
    id: "hi-ww2-002", topic: "Second World War", d: 1,
    q: "The D-Day landings took place on",
    a: ["6 June 1944", "6 June 1943", "8 May 1945", "7 December 1941"],
    why: "Canadian forces landed at Juno Beach as one of the five assault sectors in Normandy.",
  },
  {
    id: "hi-ww2-003", topic: "Second World War", d: 2,
    q: "What brought the United States formally into the war?",
    a: ["The attack on Pearl Harbor in December 1941", "The fall of France", "The invasion of Poland", "The Battle of Britain"],
    why: "Germany declared war on the US days later, joining the Pacific and European conflicts into one.",
  },
  {
    id: "hi-ww2-004", topic: "Second World War", d: 2,
    q: "The Battle of Stalingrad is treated as a turning point because",
    a: ["It destroyed a German army and the eastern initiative passed to the Soviets", "It ended the war in Europe", "It was Germany's first battle of the war", "It opened a second front in the west"],
    why: "An entire army group was encircled and lost. From then on the Wehrmacht was largely retreating in the east.",
  },
  {
    id: "hi-ww2-005", topic: "Second World War", d: 2,
    q: "Victory in Europe was declared on",
    a: ["8 May 1945", "2 September 1945", "6 August 1945", "30 April 1945"],
    why: "The war in the Pacific continued until Japan's formal surrender in September.",
  },
  {
    id: "hi-cw-001", topic: "Cold War", d: 1,
    q: "NATO was founded in",
    a: ["1949", "1945", "1955", "1961"],
    why: "The Warsaw Pact formed in 1955 as the eastern counterpart.",
  },
  {
    id: "hi-cw-002", topic: "Cold War", d: 2,
    q: "The Berlin Airlift of 1948 to 1949 was a response to",
    a: ["A Soviet blockade of land routes into West Berlin", "The building of the Berlin Wall", "The Cuban Missile Crisis", "German reunification"],
    why: "Supplying a city entirely by air for months was both a logistical feat and a political statement.",
  },
  {
    id: "hi-cw-003", topic: "Cold War", d: 2,
    q: "The Cuban Missile Crisis occurred in",
    a: ["1962", "1956", "1968", "1973"],
    why: "Thirteen days of brinkmanship ended with Soviet withdrawal and a quiet American removal of missiles from Turkey.",
  },
  {
    id: "hi-cw-004", topic: "Cold War", d: 2,
    q: "The Berlin Wall fell in",
    a: ["1989", "1991", "1985", "1961"],
    why: "It had stood since 1961. The Soviet Union itself dissolved at the end of 1991.",
  },
  {
    id: "hi-cw-005", topic: "Cold War", d: 3,
    q: "Why did neither superpower attack the other directly despite decades of hostility?",
    a: ["Nuclear arsenals made any exchange suicidal for both", "They were formal allies throughout", "The United Nations forbade it", "Neither had the military capacity"],
    why: "Mutually assured destruction pushed the rivalry into proxy wars, espionage and arms racing instead.",
    deeper: [{
      level: 3,
      q: "Given that logic, why was the Korean War possible in 1950?",
      a: ["A proxy conflict let both sides contest territory below the nuclear threshold", "Neither side had nuclear weapons yet", "The Soviet Union was not involved at all", "It was fought entirely by United Nations forces"],
      why: "Limiting the geography and the participants kept the stakes below the level that would trigger escalation.",
    }],
  },
  {
    id: "hi-cw-006", topic: "Cold War", d: 2,
    q: "Sputnik, launched in 1957, alarmed the United States mainly because it showed",
    a: ["The Soviets had rockets capable of reaching any point on Earth", "Satellites could carry weapons already", "American radar was obsolete", "The Soviets had landed on the Moon"],
    why: "The same booster that lifts a satellite can deliver a warhead. The space race and the missile race were one project.",
  },
  {
    id: "hi-vn-001", topic: "Vietnam War", d: 2,
    q: "French rule in Indochina effectively ended after their defeat at",
    a: ["Dien Bien Phu in 1954", "Hue in 1968", "Saigon in 1975", "Hanoi in 1946"],
    why: "The Geneva Accords that followed divided Vietnam at the seventeenth parallel.",
  },
  {
    id: "hi-vn-002", topic: "Vietnam War", d: 2,
    q: "The Tet Offensive of 1968 mattered most because it",
    a: ["Shook American public confidence even though it was a military setback for the North", "Ended the war immediately", "Captured Saigon", "Forced China to intervene"],
    why: "A war the public had been told was nearly won suddenly looked nothing of the kind.",
  },
  {
    id: "hi-vn-003", topic: "Vietnam War", d: 2,
    q: "Saigon fell in",
    a: ["1975", "1973", "1968", "1979"],
    why: "American combat troops had withdrawn two years earlier under the Paris Peace Accords.",
  },
  {
    id: "hi-rul-001", topic: "rulers and leaders", d: 2,
    q: "Genghis Khan's empire is notable for being",
    a: ["The largest contiguous land empire in history", "Confined to modern Mongolia", "Built entirely through diplomacy", "Short of any administrative system"],
    why: "It stretched from the Pacific to eastern Europe and moved goods, people and plague along its roads.",
  },
  {
    id: "hi-rul-002", topic: "rulers and leaders", d: 2,
    q: "Peter the Great is remembered chiefly for",
    a: ["Forcing Russia toward western technology and founding St Petersburg", "Freeing the serfs", "Defeating Napoleon", "Converting Russia to Christianity"],
    why: "He wanted a navy, a warm-water outlook and a state that could compete with western Europe.",
  },
  {
    id: "hi-rul-003", topic: "rulers and leaders", d: 2,
    q: "Queen Victoria's reign is associated with",
    a: ["Britain's industrial and imperial peak in the nineteenth century", "The English Civil War", "The loss of the American colonies", "The Norman Conquest"],
    why: "She reigned from 1837 to 1901, and Canadian Confederation happened squarely in the middle of it.",
  },
];
