import type { SeedQuestion } from "../types";

/** Correct answer is always the first option; the engine shuffles when serving. */
export const physics: SeedQuestion[] = [
  {
    id: "ph-mech-001", topic: "mechanics", d: 1,
    q: "A puck slides across frictionless ice at a steady speed. What is the net force on it?",
    a: ["Zero", "A constant force pointing forward", "A force equal to its weight", "A force that grows with speed"],
    why: "Constant velocity means zero acceleration, so the forces cancel. Motion needs no force to continue — only to change.",
    deeper: [{
      level: 2,
      q: "The same puck now slows down gradually on rough ice. What changed?",
      a: ["A net backward force appeared", "Its mass increased", "Its inertia was used up", "Gravity started acting on it"],
      why: "Friction supplies a net force opposite the motion. Inertia is not a fuel that drains away.",
    }],
  },
  {
    id: "ph-mech-002", topic: "mechanics", d: 1,
    q: "What does an object's mass measure that its weight does not?",
    a: ["Its resistance to acceleration", "The gravitational pull on it", "Its volume", "Its density"],
    why: "Mass is inertia and is the same everywhere. Weight is the local gravitational force on that mass.",
  },
  {
    id: "ph-mech-003", topic: "mechanics", d: 2,
    q: "A ball on a string is whirled in a horizontal circle at constant speed. Which way does its acceleration point?",
    a: ["Toward the centre of the circle", "Along the direction of motion", "Away from the centre", "It has no acceleration"],
    why: "Speed is constant but velocity direction keeps changing, and that change points inward.",
  },
  {
    id: "ph-mech-004", topic: "mechanics", d: 2,
    q: "Cut the string on that whirling ball. What path does the ball follow next?",
    a: ["A straight line along its velocity at release", "A curve continuing the circle", "Straight outward from the centre", "Straight toward the centre"],
    why: "With the inward force gone, Newton's first law takes over and it flies off tangentially.",
  },
  {
    id: "ph-mech-005", topic: "mechanics", d: 3,
    q: "A skater spinning with arms out pulls them in and speeds up. Why?",
    a: ["Moment of inertia drops while angular momentum is conserved", "She does work against friction", "Her angular momentum increases", "Centrifugal force pushes her around faster"],
    why: "No external torque, so angular momentum stays fixed. Shrinking the moment of inertia forces the spin rate up.",
    deeper: [{
      level: 3,
      q: "Does her rotational kinetic energy stay the same through that pull-in?",
      a: ["No, it rises — her muscles do work pulling inward", "Yes, energy is always conserved", "No, it falls because she spins faster", "Yes, because no torque acts"],
      why: "Conserving angular momentum does not conserve rotational energy. Pulling mass inward against the rotation costs muscular work, which shows up as extra kinetic energy.",
    }],
  },
  {
    id: "ph-mech-006", topic: "mechanics", d: 2,
    q: "A skydiver reaches terminal velocity. What is true at that moment?",
    a: ["Drag equals weight, so acceleration is zero", "Gravity has stopped acting", "Drag exceeds weight", "The diver is momentarily weightless"],
    why: "Drag grows with speed until it balances weight. The diver keeps falling — just no longer speeding up.",
  },
  {
    id: "ph-mech-007", topic: "mechanics", d: 2,
    q: "Two balls are released from the same height, one dropped and one fired horizontally. Ignoring air, which lands first?",
    a: ["They land together", "The dropped one", "The horizontally fired one", "It depends on the horizontal speed"],
    why: "Horizontal and vertical motion are independent. Both have the same downward acceleration and the same fall height.",
  },
  {
    id: "ph-mech-008", topic: "mechanics", d: 1,
    q: "You push a wall and it does not move. How much work do you do on the wall?",
    a: ["None", "Your force times the time you push", "Your force times your mass", "Enough to heat the wall"],
    why: "Work needs displacement along the force. No movement, no work — however tired you get.",
  },
  {
    id: "ph-energy-001", topic: "energy and momentum", d: 2,
    q: "A car doubles its speed. Its kinetic energy becomes how many times larger?",
    a: ["Four", "Two", "Eight", "The square root of two"],
    why: "Kinetic energy scales with the square of speed, which is why stopping distances grow so fast.",
  },
  {
    id: "ph-energy-002", topic: "energy and momentum", d: 2,
    q: "Which quantity is conserved in every collision in an isolated system, elastic or not?",
    a: ["Momentum", "Kinetic energy", "Speed", "Temperature"],
    why: "Momentum conservation follows from Newton's third law. Kinetic energy survives only in elastic collisions.",
    deeper: [{
      level: 2,
      q: "In a perfectly inelastic collision, where does the missing kinetic energy go?",
      a: ["Into deformation, heat and sound", "It is destroyed outright", "Into extra momentum", "Into the objects' masses, measurably"],
      why: "Energy is redistributed into internal forms. Momentum has nowhere else to go, so it stays put.",
    }],
  },
  {
    id: "ph-energy-003", topic: "energy and momentum", d: 2,
    q: "Why does an airbag reduce injury in a crash?",
    a: ["It stretches the stopping time, lowering the peak force", "It reduces the change in momentum", "It absorbs the passenger's momentum permanently", "It lowers the passenger's mass"],
    why: "The momentum change is fixed by the crash. Spreading it over more time cuts the force.",
  },
  {
    id: "ph-energy-004", topic: "energy and momentum", d: 1,
    q: "A pendulum swings. Where is its kinetic energy greatest?",
    a: ["At the lowest point", "At the highest point", "Halfway up the swing", "It is constant throughout"],
    why: "Height buys potential energy; the bob trades it all back for speed at the bottom.",
  },
  {
    id: "ph-energy-005", topic: "energy and momentum", d: 3,
    q: "A rifle and its bullet get equal and opposite momentum. Why does the bullet carry far more kinetic energy?",
    a: ["Kinetic energy is momentum squared over twice the mass, so the light body gets more", "The bullet is accelerated for longer", "Momentum is not really equal", "Chemical energy goes only into the bullet"],
    why: "For the same momentum magnitude, energy is inversely proportional to mass. The heavy rifle takes the recoil gently.",
  },
  {
    id: "ph-energy-006", topic: "energy and momentum", d: 2,
    q: "Power differs from energy in that power is",
    a: ["The rate at which energy is transferred", "The total energy stored", "Energy times time", "Force times distance"],
    why: "A small motor can do the same job as a big one — it just takes longer.",
  },
  {
    id: "ph-energy-007", topic: "energy and momentum", d: 3,
    q: "Why can no heat engine convert all its input heat into work?",
    a: ["The second law requires some heat be dumped to a colder reservoir", "Friction always consumes exactly the rest", "Energy is lost, breaking conservation", "Materials cannot survive the temperatures"],
    why: "Entropy must not decrease overall, and that forces an exhaust. Efficiency is capped even for a perfect frictionless machine.",
  },
  {
    id: "ph-wave-001", topic: "waves", d: 1,
    q: "A wave's speed stays fixed and its frequency increases. What happens to its wavelength?",
    a: ["It gets shorter", "It gets longer", "It stays the same", "It doubles"],
    why: "Speed is frequency times wavelength, so at fixed speed the two trade off inversely.",
  },
  {
    id: "ph-wave-002", topic: "waves", d: 1,
    q: "Sound in air is which kind of wave?",
    a: ["Longitudinal", "Transverse", "Electromagnetic", "Standing only"],
    why: "Air is compressed and rarefied along the travel direction. Gases cannot support transverse shear.",
  },
  {
    id: "ph-wave-003", topic: "waves", d: 2,
    q: "Two identical waves meet exactly half a wavelength out of step. What do you observe?",
    a: ["Cancellation at that point", "Doubled amplitude", "A shift in frequency", "A standing wave everywhere"],
    why: "Crest lands on trough, so the displacements subtract. That is destructive interference.",
  },
  {
    id: "ph-wave-004", topic: "waves", d: 2,
    q: "An ambulance passes you with its siren on. What actually changes as it goes by?",
    a: ["The frequency you receive, not the frequency emitted", "The speed of the sound in air", "The loudness only", "The wavelength emitted by the siren"],
    why: "Relative motion compresses then stretches the arriving wavefronts. The siren itself never changes note.",
    deeper: [{
      level: 3,
      q: "A radar gun uses the same effect. What does it measure directly?",
      a: ["The frequency shift of the reflected wave", "The travel time of a pulse", "The car's kinetic energy", "The car's acceleration"],
      why: "Doppler radar reads a shift and converts it to closing speed. Time-of-flight is a different technique.",
    }],
  },
  {
    id: "ph-wave-005", topic: "waves", d: 2,
    q: "Light passes from air into glass. Which property does not change?",
    a: ["Its frequency", "Its speed", "Its wavelength", "Its direction"],
    why: "Frequency is set by the source. Slowing in the medium shortens the wavelength and bends the ray.",
  },
  {
    id: "ph-wave-006", topic: "waves", d: 2,
    q: "Why can you hear someone around a corner but not see them?",
    a: ["Sound's long wavelengths diffract around obstacles far better than light's", "Sound travels faster than light indoors", "Sound is not blocked by solids", "Light is a transverse wave, so it cannot bend"],
    why: "Diffraction is strong when wavelength is comparable to the obstacle. Metre-scale sound bends; half-micron light does not.",
  },
  {
    id: "ph-wave-007", topic: "waves", d: 3,
    q: "Why does a guitar string sound a definite note rather than noise?",
    a: ["Fixed ends allow only standing waves at specific harmonic frequencies", "The string vibrates at one frequency only, with no harmonics", "The soundboard filters out everything but one tone", "Tension forces the air to resonate at a single pitch"],
    why: "Boundary conditions quantise the allowed modes. The fundamental plus its harmonics give pitch and timbre.",
  },
  {
    id: "ph-elec-001", topic: "electricity", d: 1,
    q: "Electric current is best described as",
    a: ["The rate of flow of electric charge", "The push that drives charges", "Resistance to charge flow", "Energy stored per charge"],
    why: "Current counts charge per second. The push is voltage.",
  },
  {
    id: "ph-elec-002", topic: "electricity", d: 2,
    q: "Add a second identical resistor in parallel with the first. The total resistance",
    a: ["Falls to half the original", "Doubles", "Stays the same", "Rises slightly"],
    why: "Parallel paths give charge more routes. Total resistance is always below the smallest branch.",
  },
  {
    id: "ph-elec-003", topic: "electricity", d: 2,
    q: "What does a capacitor fundamentally store?",
    a: ["Energy in an electric field between separated charges", "Current, for later release", "Magnetic energy in a coil", "Charge that it creates itself"],
    why: "The plates hold equal and opposite charge; the field between them holds the energy. Net charge stays zero.",
  },
  {
    id: "ph-elec-004", topic: "electricity", d: 2,
    q: "Why is a bird on a single high-voltage line unharmed?",
    a: ["Both feet sit at nearly the same potential, so almost no current flows through it", "Feathers insulate it", "The line carries no current while the bird sits there", "Birds are immune to electric shock"],
    why: "Current needs a potential difference across the body. Touching a second line or a pole would be fatal.",
    deeper: [{
      level: 3,
      q: "What makes a downed live wire dangerous to walk near, even without touching it?",
      a: ["Current spreading through the ground creates a voltage difference between your feet", "The wire radiates enough energy to ionise the air", "Static charge builds on your clothing", "Ground is a perfect conductor and carries full line voltage"],
      why: "That is step potential. Shuffling with feet together is the standard escape technique.",
    }],
  },
  {
    id: "ph-elec-005", topic: "electricity", d: 2,
    q: "Double the voltage across a fixed resistor. The power it dissipates",
    a: ["Quadruples", "Doubles", "Halves", "Stays the same"],
    why: "Both current and voltage double, and power is their product.",
  },
  {
    id: "ph-elec-006", topic: "electricity", d: 3,
    q: "Why does a superconductor carry current with no voltage drop?",
    a: ["Paired electrons move without scattering, so resistance is exactly zero", "Its resistance is merely very small", "It stores the lost energy magnetically", "Electrons move faster than in copper"],
    why: "Below the critical temperature the charge carriers form pairs that cannot scatter off the lattice. Zero means zero, not tiny.",
  },
  {
    id: "ph-mag-001", topic: "magnetism", d: 1,
    q: "Outside a bar magnet, field lines run",
    a: ["From the north pole to the south pole", "From south to north", "Radially outward from both poles", "In closed loops that avoid the poles"],
    why: "They continue south to north inside the magnet, making every line a closed loop.",
  },
  {
    id: "ph-mag-002", topic: "magnetism", d: 2,
    q: "Break a bar magnet in half. What do you get?",
    a: ["Two smaller magnets, each with both poles", "An isolated north and an isolated south", "Two unmagnetised pieces", "One magnet and one monopole"],
    why: "No isolated magnetic charge has ever been found, so poles always come in pairs.",
  },
  {
    id: "ph-mag-003", topic: "magnetism", d: 3,
    q: "A charged particle moves through a magnetic field. Why can that magnetic force never change its speed?",
    a: ["The force is always perpendicular to the velocity, so it does no work", "Magnetic fields carry no energy", "The force is too weak to matter", "It changes speed but not direction"],
    why: "A perpendicular force only steers. That is why cyclotrons need an electric field to accelerate.",
  },
  {
    id: "ph-mag-004", topic: "magnetism", d: 2,
    q: "What produces the magnetic field around a current-carrying wire?",
    a: ["The moving charges themselves", "The wire's resistance", "Static charge on the insulation", "The voltage source alone"],
    why: "Moving charge is the only source of magnetism, right down to electron spin in a bar magnet.",
  },
  {
    id: "ph-ind-001", topic: "induction", d: 2,
    q: "What must happen for a coil to develop an induced voltage?",
    a: ["The magnetic flux through it must change", "A strong steady field must be present", "The coil must carry current already", "The coil must be superconducting"],
    why: "Faraday's law depends on the rate of change of flux, not the flux itself.",
  },
  {
    id: "ph-ind-002", topic: "induction", d: 2,
    q: "Push a magnet toward a closed loop. The induced current flows so that it",
    a: ["Opposes the magnet's approach", "Pulls the magnet in faster", "Has no effect on the magnet", "Heats the magnet directly"],
    why: "Lenz's law is energy conservation in disguise — you must do work to push against that opposition.",
    deeper: [{
      level: 3,
      q: "Drop a strong magnet down a copper pipe and it falls slowly. Why?",
      a: ["Induced eddy currents in the copper oppose the changing flux", "Copper is weakly magnetic and attracts it", "Air is trapped beneath the magnet", "Static charge builds on the pipe wall"],
      why: "The falling magnet induces circulating currents that push back. Copper is not ferromagnetic at all.",
    }],
  },
  {
    id: "ph-ind-003", topic: "induction", d: 2,
    q: "Why does a transformer do nothing with a steady DC input?",
    a: ["Steady current gives constant flux, and constant flux induces nothing", "DC cannot flow through copper windings", "The iron core saturates instantly with DC", "Transformers need a magnetic core that only AC provides"],
    why: "Induction needs change. Switching or alternating the current is what makes a transformer work.",
  },
  {
    id: "ph-ind-004", topic: "induction", d: 1,
    q: "A generator and a motor are built from the same parts. What is the difference in use?",
    a: ["A generator turns motion into current; a motor turns current into motion", "A generator needs permanent magnets and a motor does not", "Only the motor uses induction", "A generator runs on DC only"],
    why: "They are the same machine run in opposite directions, which is why motors can brake regeneratively.",
  },
  {
    id: "ph-mod-001", topic: "modern physics", d: 2,
    q: "Shine brighter light of the same colour on a metal. The ejected electrons",
    a: ["Are more numerous but no more energetic", "Each carry more kinetic energy", "Come out at higher frequency", "Stop being emitted"],
    why: "Each photon acts alone, so its energy — set by frequency — fixes the electron's energy. Intensity only adds photons.",
    deeper: [{
      level: 3,
      q: "Below a certain frequency, no electrons come out at all, however bright the light. What does that tell you?",
      a: ["Light delivers energy in discrete quanta that must individually exceed the work function", "The metal reflects low frequencies perfectly", "The electrons need time to accumulate energy", "Low-frequency light carries no energy"],
      why: "This threshold is the observation that forced the photon picture on physics.",
    }],
  },
  {
    id: "ph-mod-002", topic: "modern physics", d: 1,
    q: "A photon's energy is set by which property of the light?",
    a: ["Its frequency", "Its intensity", "Its polarisation", "Its beam width"],
    why: "Energy is Planck's constant times frequency. Blue photons beat red ones one for one.",
  },
  {
    id: "ph-mod-003", topic: "modern physics", d: 2,
    q: "Electrons fired one at a time through a double slit build up what pattern?",
    a: ["An interference pattern of bright and dark bands", "Two sharp bands behind the slits", "A single central blob", "A random scatter with no structure"],
    why: "Each electron interferes with itself. Matter has wave character, which is de Broglie's point.",
  },
  {
    id: "ph-mod-004", topic: "modern physics", d: 2,
    q: "The uncertainty principle says that position and momentum",
    a: ["Cannot both be known precisely, no matter how good the instrument", "Can be measured precisely but not at once", "Are uncertain only for large objects", "Are limited by the experimenter's skill"],
    why: "It is a property of quantum states, not a measurement flaw. Sharpening one distribution necessarily broadens the other.",
  },
  {
    id: "ph-mod-005", topic: "modern physics", d: 1,
    q: "After two half-lives, how much of a radioactive sample remains undecayed?",
    a: ["A quarter", "A half", "None", "An eighth"],
    why: "Each half-life halves what is left, so the decay curve never quite reaches zero.",
  },
  {
    id: "ph-mod-006", topic: "modern physics", d: 2,
    q: "Which radiation is stopped by a sheet of paper?",
    a: ["Alpha", "Beta", "Gamma", "Neutron"],
    why: "Alpha particles are heavy and highly charged, so they lose energy almost immediately — dangerous mainly if inhaled.",
  },
  {
    id: "ph-mod-007", topic: "modern physics", d: 2,
    q: "What distinguishes fusion from fission?",
    a: ["Fusion joins light nuclei; fission splits heavy ones", "Fusion splits nuclei and fission joins them", "Only fission releases energy", "Fusion works only with uranium"],
    why: "Both move nuclei toward iron, the peak of binding energy per nucleon, and release energy doing it.",
  },
  {
    id: "ph-rel-001", topic: "relativity", d: 1,
    q: "Special relativity's starting postulate about light is that its speed in vacuum is",
    a: ["The same for every inertial observer", "Measured relative to the source", "Relative to the fixed ether", "Different for different colours"],
    why: "Everything strange in special relativity follows from taking that invariance seriously.",
  },
  {
    id: "ph-rel-002", topic: "relativity", d: 2,
    q: "A clock flies past you at high speed. Compared with your clock, it",
    a: ["Ticks slower from your point of view", "Ticks faster", "Ticks at the same rate", "Stops entirely"],
    why: "Time dilation is symmetric — the traveller says the same about your clock. There is no privileged frame.",
  },
  {
    id: "ph-rel-003", topic: "relativity", d: 2,
    q: "Why can no object with mass reach the speed of light?",
    a: ["Its inertia grows without limit, so the energy needed diverges", "Light would collide with it", "Space runs out at that speed", "Its mass drops to zero first"],
    why: "The energy required approaches infinity as speed approaches c. Only massless things travel at c.",
  },
  {
    id: "ph-rel-004", topic: "relativity", d: 3,
    q: "In general relativity, what does gravity actually consist of?",
    a: ["Curvature of spacetime produced by mass and energy", "A force carried between masses by gravitons in flat space", "An attraction that propagates instantly", "A property only of very massive objects"],
    why: "Free-falling bodies follow the straightest available paths through curved spacetime — no force needed.",
    deeper: [{
      level: 3,
      q: "GPS satellites correct their clocks for relativity. Which effect dominates for them?",
      a: ["Weaker gravity up there speeds their clocks more than their orbital speed slows them", "Their speed slows the clocks more than gravity speeds them", "Only special relativity matters at orbital altitude", "Neither matters; the correction is for signal delay"],
      why: "The two effects act in opposite directions and gravitational time dilation wins, by tens of microseconds a day.",
    }],
  },
  {
    id: "ph-rel-005", topic: "relativity", d: 2,
    q: "E = mc² is best read as the statement that",
    a: ["Mass and energy are the same thing in different units", "Mass can be converted into energy only in reactors", "Energy has weight only at high speed", "Light has mass"],
    why: "A hot object is measurably heavier than a cold one. Nuclear reactions just make the effect large enough to notice.",
  },
];
