import type { SeedQuestion } from "../types";

export const rf: SeedQuestion[] = [
  {
    id: "rf-fund-001", topic: "radio fundamentals", d: 1,
    q: "Radio waves and visible light differ in frequency. What else differs?",
    a: ["Nothing fundamental — both are electromagnetic waves", "Radio needs a medium, light does not", "Light is transverse, radio is longitudinal", "Radio travels slower in vacuum"],
    why: "Same phenomenon, same speed in vacuum. Only the frequency, and therefore how matter responds, changes.",
  },
  {
    id: "rf-fund-002", topic: "radio fundamentals", d: 1,
    q: "A signal moves from 100 MHz to 400 MHz. Its wavelength",
    a: ["Shrinks to a quarter", "Grows four times", "Halves", "Stays the same"],
    why: "Wavelength is the speed of light divided by frequency, so the two are inversely proportional.",
  },
  {
    id: "rf-fund-003", topic: "electromagnetic spectrum", d: 1,
    q: "Which of these sits at the highest frequency?",
    a: ["Gamma rays", "Microwaves", "Infrared", "Ultraviolet"],
    why: "The order runs radio, microwave, infrared, visible, ultraviolet, X-ray, gamma.",
  },
  {
    id: "rf-fund-004", topic: "electromagnetic spectrum", d: 2,
    q: "Why is the 2.4 GHz band so crowded worldwide?",
    a: ["It is a licence-free ISM band available in nearly every country", "It is the only band that penetrates walls", "It offers the highest possible data rate", "Regulators reserved it for long-range links"],
    why: "Free access plus global availability attracted Wi-Fi, Bluetooth, Zigbee, microwave ovens and more.",
  },
  {
    id: "rf-fund-005", topic: "radio fundamentals", d: 2,
    q: "What does a signal's bandwidth describe?",
    a: ["The span of frequencies it occupies", "Its transmit power", "How far it can travel", "Its centre frequency"],
    why: "More information per second demands more spectrum, which is why fast links need wide channels.",
  },
  {
    id: "rf-db-001", topic: "dB and dBm", d: 1,
    q: "An amplifier doubles the power of a signal. What gain is that in decibels?",
    a: ["About 3 dB", "About 6 dB", "About 10 dB", "About 2 dB"],
    why: "Every 3 dB is roughly a factor of two in power; 10 dB is a factor of ten.",
    deeper: [{
      level: 2,
      q: "A cable loses 6 dB. What fraction of the input power reaches the far end?",
      a: ["A quarter", "A half", "A tenth", "A sixteenth"],
      why: "Two 3 dB steps, so two halvings. Decibels add where ratios multiply.",
    }],
  },
  {
    id: "rf-db-002", topic: "dB and dBm", d: 2,
    q: "What does 0 dBm mean?",
    a: ["One milliwatt", "One watt", "No power at all", "A gain of zero relative to a dipole"],
    why: "dBm is an absolute level referenced to 1 mW, so 30 dBm is one watt.",
  },
  {
    id: "rf-db-003", topic: "dB and dBm", d: 2,
    q: "Why is dB unitless while dBm is not?",
    a: ["dB expresses a ratio; dBm fixes the reference at 1 mW", "dB is for voltage and dBm is for power", "dBm is used only for antennas", "dB applies only to losses"],
    why: "You can add a dB gain to a dBm level and get dBm. Adding two dBm figures is meaningless.",
  },
  {
    id: "rf-db-004", topic: "dB and dBm", d: 2,
    q: "An antenna is rated 6 dBi. What does the 'i' reference?",
    a: ["An isotropic radiator that would spread power equally in all directions", "An ideal half-wave dipole", "The installed feedline", "An industry test antenna"],
    why: "dBd references a dipole instead, and a dipole is about 2.15 dBi, so the two scales differ by that much.",
  },
  {
    id: "rf-ant-001", topic: "antennas", d: 3,
    q: "Why does raising antenna gain not increase the power your transmitter puts out?",
    a: ["Gain redistributes the same power into a narrower beam", "Gain converts feedline loss into extra power", "Gain amplifies the signal using the antenna's own supply", "It does increase output power, by definition"],
    why: "An antenna is passive. It concentrates radiation in some directions by starving others.",
    deeper: [{
      level: 3,
      q: "So what is the practical cost of a very high-gain antenna on a moving vehicle?",
      a: ["The narrow beam must stay aimed, so tilting or turning drops the link", "It draws more current from the radio", "It raises the noise floor of the receiver", "It only works on one frequency band"],
      why: "Narrow beamwidth is the price of gain. Mobile installations usually trade gain for coverage.",
    }],
  },
  {
    id: "rf-ant-002", topic: "antennas", d: 2,
    q: "A quarter-wave whip for 145 MHz is roughly how long?",
    a: ["About half a metre", "About two metres", "About five centimetres", "About four metres"],
    why: "A 145 MHz wavelength is near two metres, so a quarter of it is close to 50 cm.",
  },
  {
    id: "rf-ant-003", topic: "antennas", d: 2,
    q: "A handheld with a vertical whip talks to a station using a horizontal dipole. What is the main penalty?",
    a: ["Polarisation mismatch loss", "Impedance mismatch", "Doppler shift", "Extra free-space path loss"],
    why: "Cross-polarised antennas can lose 20 dB or more. Matching polarisation is free signal.",
  },
  {
    id: "rf-ant-004", topic: "antennas", d: 2,
    q: "What makes a Yagi directional?",
    a: ["Parasitic reflector and director elements reshape the pattern", "It is longer than a dipole", "It is fed at both ends", "It uses a ferrite core"],
    why: "Only the driven element is connected. The others re-radiate with phases that reinforce forward and cancel backward.",
  },
  {
    id: "rf-ant-005", topic: "antennas", d: 2,
    q: "Why does a ground-plane antenna need radials?",
    a: ["They act as the missing half of the antenna, giving the current somewhere to return", "They keep the mast from corroding", "They shield the feedline from noise", "They tune the antenna to multiple bands"],
    why: "A quarter-wave vertical works against an image in the ground plane. Poor radials waste power as ground loss.",
  },
  {
    id: "rf-ant-006", topic: "antennas", d: 3,
    q: "A tiny antenna on a low frequency is inefficient mostly because",
    a: ["Its radiation resistance is far smaller than its loss resistance", "Low frequencies carry less energy", "Short antennas cannot be impedance matched at all", "The wavelength is too short for it"],
    why: "Electrically small antennas couple weakly to free space, so most of the input heats the conductor and matching network.",
  },
  {
    id: "rf-mod-001", topic: "modulation", d: 1,
    q: "In frequency modulation, what carries the information?",
    a: ["Variations in the carrier's frequency", "Variations in the carrier's amplitude", "Variations in the carrier's power", "The gaps between bursts"],
    why: "Amplitude stays roughly constant, which is why FM shrugs off amplitude noise.",
  },
  {
    id: "rf-mod-002", topic: "modulation", d: 2,
    q: "Two FM stations on the same frequency reach your receiver, one much stronger. What do you hear?",
    a: ["Only the stronger one, cleanly", "Both mixed together", "A loud heterodyne whistle", "Silence from mutual cancellation"],
    why: "That is the capture effect. AM receivers, by contrast, would let you hear both.",
  },
  {
    id: "rf-mod-003", topic: "modulation", d: 2,
    q: "What does QAM vary to pack more bits into each symbol?",
    a: ["Both amplitude and phase", "Frequency and phase", "Amplitude and bandwidth", "Polarisation and phase"],
    why: "A denser constellation carries more bits per symbol but needs a better signal-to-noise ratio to keep the points apart.",
    deeper: [{
      level: 3,
      q: "A link switches from 64-QAM down to QPSK when conditions worsen. What has it traded?",
      a: ["Data rate, in exchange for robustness against noise", "Bandwidth, in exchange for power", "Latency, in exchange for range", "Frequency, in exchange for bandwidth"],
      why: "Adaptive modulation keeps the link alive by moving to a sparser constellation that tolerates a lower SNR.",
    }],
  },
  {
    id: "rf-mod-004", topic: "modulation", d: 2,
    q: "Why does OFDM split data across many narrow subcarriers?",
    a: ["Each narrow subcarrier sees a flat channel, so multipath is easy to equalise", "It reduces total bandwidth needed", "It removes the need for error correction", "It lets one transmitter serve many frequencies at once"],
    why: "Wideband multipath becomes a manageable per-subcarrier correction. It is the backbone of Wi-Fi, LTE and DAB.",
  },
  {
    id: "rf-mod-005", topic: "modulation", d: 2,
    q: "Single sideband is used on HF voice mainly because it",
    a: ["Uses less bandwidth and puts all the power into useful signal", "Sounds more natural than FM", "Is easier to demodulate", "Is immune to fading"],
    why: "Suppressing the carrier and one sideband saves spectrum and power — worth the tuning fussiness on a crowded band.",
  },
  {
    id: "rf-prop-001", topic: "propagation", d: 2,
    q: "Double the distance on a free-space link. Received power drops by",
    a: ["6 dB", "3 dB", "10 dB", "20 dB"],
    why: "Power spreads over a sphere, so it falls with the square of distance — a factor of four, or 6 dB.",
  },
  {
    id: "rf-prop-002", topic: "propagation", d: 2,
    q: "Why do HF signals sometimes reach the other side of the planet?",
    a: ["The ionosphere refracts them back toward Earth, letting them skip", "They follow the curvature by diffraction alone", "They pass through the Earth", "Satellites relay them automatically"],
    why: "Ionospheric refraction depends on frequency, time of day and solar activity, which is why HF conditions shift hourly.",
  },
  {
    id: "rf-prop-003", topic: "propagation", d: 2,
    q: "At UHF, what usually limits range on the ground?",
    a: ["Line of sight and obstructions", "Ionospheric absorption", "Rain fade", "Regulatory power limits alone"],
    why: "Above about 50 MHz, signals mostly go where you can see. Height buys more range than power.",
  },
  {
    id: "rf-prop-004", topic: "propagation", d: 3,
    q: "A microwave link has clear line of sight but still fades when a building rises beside the path. Why?",
    a: ["The obstruction intrudes into the first Fresnel zone", "The building reflects the signal back to the transmitter", "It raises the receiver's noise floor", "It changes the polarisation"],
    why: "The path needs a clear ellipsoid around the sight line, not just an unblocked straight line.",
  },
  {
    id: "rf-prop-005", topic: "propagation", d: 2,
    q: "Moving a handheld a few centimetres restores a dropped signal. What was happening?",
    a: ["Multipath reflections were cancelling at that exact spot", "The antenna had overheated", "The transmitter changed channel", "Rain fade cleared"],
    why: "Reflected copies arrive out of phase and create nulls spaced roughly half a wavelength apart.",
  },
  {
    id: "rf-prop-006", topic: "propagation", d: 2,
    q: "Rain fade becomes a serious design factor mainly above",
    a: ["About 10 GHz", "About 100 MHz", "About 1 MHz", "About 500 MHz"],
    why: "Raindrops are a meaningful fraction of a wavelength up there, so they absorb and scatter. Satellite Ku and Ka links plan for it.",
  },
  {
    id: "rf-tl-001", topic: "transmission lines", d: 2,
    q: "Why is most radio coax made to 50 ohms?",
    a: ["It is a practical compromise between lowest loss and highest power handling", "It matches the impedance of free space", "It is the resistance of a half-wave dipole", "It was the cheapest to manufacture"],
    why: "Minimum loss lands near 77 ohms and peak power handling near 30, so 50 splits the difference.",
  },
  {
    id: "rf-tl-002", topic: "transmission lines", d: 2,
    q: "A high SWR on a feedline means",
    a: ["A significant share of the forward power is being reflected back", "The feedline is too long", "The transmitter is producing harmonics", "The antenna is receiving interference"],
    why: "Reflection comes from an impedance mismatch at the load. The reflected power never leaves the antenna.",
    deeper: [{
      level: 3,
      q: "Someone fixes a high SWR by adding a long lossy cable. Why is the meter reading now fine but the station not?",
      a: ["Cable loss attenuates the reflection, hiding the mismatch while wasting power as heat", "The extra cable actually matches the antenna", "Longer cable lowers the antenna's resonant frequency", "SWR meters are inaccurate on long runs"],
      why: "Loss flatters the SWR reading in both directions. The mismatch is unchanged; you just cannot see it.",
    }],
  },
  {
    id: "rf-tl-003", topic: "transmission lines", d: 2,
    q: "Coax loss changes with frequency in which way?",
    a: ["It rises as frequency rises", "It falls as frequency rises", "It is flat across all bands", "It depends only on cable length"],
    why: "Skin effect and dielectric loss both worsen with frequency, so short thick cable matters most at microwave.",
  },
  {
    id: "rf-tl-004", topic: "transmission lines", d: 3,
    q: "What is a balun for?",
    a: ["Connecting a balanced antenna to an unbalanced feedline without current on the coax shield", "Stepping voltage up for transmission", "Blocking DC from reaching the antenna", "Tuning the antenna to resonance"],
    why: "Without one the outside of the shield radiates, distorting the pattern and bringing RF back into the shack.",
  },
  {
    id: "rf-sdr-001", topic: "SDR", d: 2,
    q: "What does the software in a software-defined radio actually replace?",
    a: ["Filtering, mixing and demodulation that used to be fixed hardware", "The antenna", "The analogue-to-digital converter", "The power amplifier"],
    why: "Once the signal is digitised, changing mode or bandwidth is a code change rather than a board change.",
  },
  {
    id: "rf-sdr-002", topic: "SDR", d: 2,
    q: "Sampling a signal below the Nyquist rate produces",
    a: ["Aliasing, where high frequencies masquerade as low ones", "Simple attenuation", "Extra bandwidth", "Improved dynamic range"],
    why: "An anti-aliasing filter ahead of the converter is what stops out-of-band energy folding into your passband.",
  },
  {
    id: "rf-sdr-003", topic: "SDR", d: 3,
    q: "Why do SDRs sample in I and Q rather than a single real stream?",
    a: ["The pair preserves both magnitude and phase, so positive and negative offsets stay distinct", "It doubles the sample rate for free", "It halves the noise figure", "It removes the need for a local oscillator"],
    why: "Complex baseband lets you tell a signal above the tuned frequency from one below it, and makes demodulation arithmetic simple.",
  },
  {
    id: "rf-sdr-004", topic: "SDR", d: 2,
    q: "A strong FM broadcast station appears as a copy inside an unrelated band on your SDR. The likely cause is",
    a: ["Front-end overload creating intermodulation products", "A genuine pirate transmitter", "Antenna polarisation error", "Sample clock drift"],
    why: "A wideband front end has limited dynamic range. An attenuator or a band-stop filter usually clears it.",
  },
  {
    id: "rf-wifi-001", topic: "Wi-Fi", d: 1,
    q: "In the 2.4 GHz band, which channel set does not overlap?",
    a: ["1, 6 and 11", "1, 5 and 9", "2, 7 and 12", "Any three channels three apart"],
    why: "Each channel is about 20 MHz wide on 5 MHz spacing, so you need five channels of separation.",
  },
  {
    id: "rf-wifi-002", topic: "Wi-Fi", d: 2,
    q: "Wi-Fi devices avoid collisions by",
    a: ["Listening before transmitting and backing off randomly", "Detecting collisions mid-transmission and aborting", "Taking scheduled turns assigned by the router", "Transmitting on separate frequencies per device"],
    why: "A radio cannot easily hear while it transmits, so Wi-Fi avoids collisions rather than detecting them like wired Ethernet.",
    deeper: [{
      level: 3,
      q: "Two clients can each hear the access point but not each other, and throughput collapses. What is the fix?",
      a: ["RTS/CTS handshaking, so the access point clears the air for each sender", "Raising both clients' transmit power to maximum", "Switching both to the same channel width", "Disabling encryption to shorten frames"],
      why: "That is the hidden node problem. The short handshake makes every station aware of a transmission it cannot hear.",
    }],
  },
  {
    id: "rf-wifi-003", topic: "Wi-Fi", d: 2,
    q: "Why does 5 GHz Wi-Fi usually carry more throughput but less range than 2.4 GHz?",
    a: ["Wider channels and less congestion, but worse penetration through walls", "Higher legal transmit power and greater path loss", "Better modulation and slower processors", "Fewer clients and lower antenna gain"],
    why: "Higher frequencies attenuate faster through building materials while offering more contiguous spectrum.",
  },
  {
    id: "rf-wifi-004", topic: "Wi-Fi", d: 2,
    q: "What does MIMO exploit to raise throughput?",
    a: ["Multipath, by sending independent streams over multiple antennas", "Higher transmit power per antenna", "Wider channels only", "Directional beam steering alone"],
    why: "The reflections that once only caused fading become separate spatial channels.",
  },
  {
    id: "rf-bt-001", topic: "Bluetooth", d: 2,
    q: "Bluetooth shares the 2.4 GHz band with Wi-Fi. How does it cope?",
    a: ["It hops rapidly between narrow channels", "It transmits at much higher power", "It uses a licensed sub-band", "It only transmits when Wi-Fi is idle"],
    why: "Frequency hopping means interference on any one channel costs only a packet, and adaptive hopping skips busy channels entirely.",
  },
  {
    id: "rf-bt-002", topic: "Bluetooth", d: 2,
    q: "Bluetooth Low Energy uses three dedicated channels for",
    a: ["Advertising, so devices can be discovered cheaply", "Audio streaming", "Firmware updates", "Error correction"],
    why: "Keeping discovery on three fixed channels lets a sensor wake briefly, shout, and sleep again on a coin cell.",
  },
  {
    id: "rf-bt-003", topic: "Bluetooth", d: 2,
    q: "Why is classic Bluetooth a poor fit for a battery sensor that reports once a minute?",
    a: ["Maintaining its connection costs far more energy than the data is worth", "It cannot transmit small packets", "Its range is too short", "It has no encryption"],
    why: "BLE was designed precisely for that duty cycle: connect, send a few bytes, drop back to sleep.",
  },
  {
    id: "rf-lora-001", topic: "LoRa and LoRaWAN", d: 2,
    q: "LoRa achieves long range at low power mainly through",
    a: ["Chirp spread spectrum, which is decodable below the noise floor", "Very high transmit power", "Directional antennas on every node", "Extremely wide channels"],
    why: "Spreading gain lets the receiver dig a slow signal out from under the noise.",
  },
  {
    id: "rf-lora-002", topic: "LoRa and LoRaWAN", d: 2,
    q: "Raising the LoRa spreading factor buys range at the cost of",
    a: ["Much longer airtime and lower data rate", "Higher power consumption per second", "Narrower bandwidth only", "Weaker encryption"],
    why: "Each step up roughly doubles time on air, which also eats into duty-cycle allowances and battery life.",
    deeper: [{
      level: 3,
      q: "A LoRaWAN network server tells distant nodes to use a high spreading factor and nearby nodes a low one. What is that mechanism called?",
      a: ["Adaptive data rate", "Frequency hopping", "Listen before talk", "Beacon scheduling"],
      why: "ADR keeps close nodes fast and quiet so they do not hog airtime the far nodes need.",
    }],
  },
  {
    id: "rf-lora-003", topic: "LoRa and LoRaWAN", d: 2,
    q: "In a LoRaWAN Class A device, when can the server send data down?",
    a: ["Only in short windows just after the device transmits", "At any time", "Only during scheduled beacons", "Never — the link is uplink only"],
    why: "The radio sleeps the rest of the time, which is what makes years on a battery possible.",
  },
  {
    id: "rf-lora-004", topic: "LoRa and LoRaWAN", d: 2,
    q: "LoRa and LoRaWAN differ in that LoRa is",
    a: ["The radio modulation, while LoRaWAN is the network protocol built on it", "The commercial brand and LoRaWAN the open version", "For point to point and LoRaWAN for satellites", "An older version of LoRaWAN"],
    why: "You can use LoRa radios peer to peer without any LoRaWAN stack at all.",
  },
  {
    id: "rf-gnss-001", topic: "GNSS", d: 2,
    q: "Why does a GPS receiver need four satellites for a 3D fix, not three?",
    a: ["The fourth solves for the receiver's own clock error", "The fourth confirms the answer", "Three cannot cover the sky", "The fourth supplies the almanac"],
    why: "A cheap crystal cannot keep atomic-clock time, so the unknown clock offset becomes a fourth variable.",
    deeper: [{
      level: 3,
      q: "A dual-frequency receiver is more accurate mainly because it can",
      a: ["Measure and remove the ionosphere's frequency-dependent delay", "Hear twice as many satellites", "Transmit back to the satellites", "Use a more precise internal clock"],
      why: "Ionospheric delay is the largest remaining error for a single-frequency receiver, and it scales with frequency.",
    }],
  },
  {
    id: "rf-gnss-002", topic: "GNSS", d: 2,
    q: "What does a GNSS receiver actually measure from each satellite?",
    a: ["The travel time of the signal, converted to a range", "The satellite's bearing", "The Doppler shift alone", "The signal strength"],
    why: "Ranges to known positions give trilateration. Doppler helps with velocity and acquisition, but position comes from timing.",
  },
  {
    id: "rf-gnss-003", topic: "GNSS", d: 2,
    q: "Why does a first fix take much longer in a city street than in an open field?",
    a: ["Buildings block satellites and reflect signals, corrupting the timing", "Urban receivers use a different constellation", "Interference from streetlights", "Satellites avoid urban areas"],
    why: "Urban canyon multipath adds fake path length, and fewer satellites in view weakens the geometry.",
  },
  {
    id: "rf-mesh-001", topic: "Meshtastic", d: 2,
    q: "What makes Meshtastic work with no cell network or internet?",
    a: ["Nodes relay each other's LoRa packets in a mesh", "Each node has a satellite uplink", "It uses shortwave skip propagation", "Phones connect directly over Wi-Fi"],
    why: "Every node is a repeater, so coverage grows with the number of participants rather than with infrastructure.",
  },
  {
    id: "rf-mesh-002", topic: "Meshtastic", d: 2,
    q: "Why does Meshtastic carry text and position rather than voice?",
    a: ["LoRa's data rate is far too low for real-time audio", "Voice is legally restricted on those bands", "The hardware has no audio codec", "Voice would break the encryption"],
    why: "A LoRa channel moves hundreds of bits per second at long range — fine for a short message, hopeless for speech.",
  },
  {
    id: "rf-mesh-003", topic: "Meshtastic", d: 3,
    q: "Why does a Meshtastic mesh impose a hop limit on messages?",
    a: ["Unbounded rebroadcasting would saturate the shared channel", "Range beyond a few hops is impossible", "Encryption expires after several hops", "Batteries cannot support more hops"],
    why: "In a flooding mesh, every extra hop multiplies airtime. The limit keeps a busy channel usable.",
  },
];
